In [1]:
import os
import math
import time
import random
import datetime
import operator 
import numpy as np 
import pandas as pd

# DATA PREPROCESSING:

In [2]:
confirmed_cases = pd.read_csv('COVID-19-Dataset/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')

In [3]:
confirmed_cases

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,63819,64122,64575,65080,65486,65728,66275,66903,67743,68366
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,132071,132095,132118,132153,132176,132209,132215,132229,132244,132264
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,125693,125896,126156,126434,126651,126860,127107,127361,127646,127926
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,13569,13569,13569,13569,13569,13569,13569,13664,13671,13682
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,31045,31438,31661,31909,32149,32441,32623,32933,33338,33607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,NaN,Vietnam,14.058324,108.277199,0,2,2,2,2,2,...,4512,4720,4809,4941,5119,5275,5404,5931,6086,6356
272,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,304074,304532,304532,304968,305201,305201,305777,306334,306795,306795
273,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,6586,6593,6613,6632,6649,6658,6662,6670,6688,6696
274,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,92520,92630,92754,92920,93106,93201,93279,93428,93627,93947
275,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,38595,38612,38635,38664,38679,38682,38696,38706,38819,38854

In [4]:
confirmed_cases.head(10)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,63819,64122,64575,65080,65486,65728,66275,66903,67743,68366
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,132071,132095,132118,132153,132176,132209,132215,132229,132244,132264
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,125693,125896,126156,126434,126651,126860,127107,127361,127646,127926
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,13569,13569,13569,13569,13569,13569,13569,13664,13671,13682
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,31045,31438,31661,31909,32149,32441,32623,32933,33338,33607
5,NaN,Antigua and Barbuda,17.06080,-61.796400,0,0,0,0,0,0,...,1251,1252,1255,1255,1257,1257,1258,1258,1258,1258
6,NaN,Argentina,-38.41610,-63.616700,0,0,0,0,0,0,...,3371508,3411160,3447044,3482512,3514683,3539484,3562135,3586736,3622135,3663215
7,NaN,Armenia,40.06910,45.038200,0,0,0,0,0,0,...,221139,221368,221559,221699,221880,221948,221982,222139,222269,222409
8,Australian Capital Territory,Australia,-35.47350,149.012400,0,0,0,0,0,0,...,124,124,124,124,124,124,124,124,124,124
9,New South Wales,Australia,-33.86880,151.209300,0,0,0,0,3,4,...,5565,5567,5567,5568,5570,5572,5574,5576,5576,5579

In [5]:
deaths_reported = pd.read_csv('COVID-19-Dataset/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')

In [6]:
deaths_reported.head(10)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,2751,2762,2772,2782,2792,2802,2812,2836,2855,2869
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,2436,2438,2440,2441,2442,2444,2445,2447,2447,2447
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,3388,3395,3401,3405,3411,3418,3426,3433,3440,3448
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,127,127,127,127,127,127,127,127,127,127
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,685,696,704,709,715,725,731,735,742,745
5,NaN,Antigua and Barbuda,17.06080,-61.796400,0,0,0,0,0,0,...,42,42,42,42,42,42,42,42,42,42
6,NaN,Argentina,-38.41610,-63.616700,0,0,0,0,0,0,...,71771,72265,72699,73391,73688,74063,74480,75056,75588,76135
7,NaN,Armenia,40.06910,45.038200,0,0,0,0,0,0,...,4346,4357,4364,4371,4386,4392,4394,4400,4411,4416
8,Australian Capital Territory,Australia,-35.47350,149.012400,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
9,New South Wales,Australia,-33.86880,151.209300,0,0,0,0,0,0,...,54,54,54,54,54,54,54,54,54,54

In [7]:
recovered_cases = pd.read_csv('COVID-19-Dataset/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')

In [8]:
recovered_cases.head(10)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,55118,55529,55687,55790,55889,56035,56295,56518,56711,56962
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,126405,127240,127869,128425,128601,128732,128826,128907,128978,129042
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,87609,87746,87902,88066,88208,88346,88497,88672,88861,89040
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,13234,13234,13234,13234,13234,13234,13234,13263,13381,13405
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,26013,26458,26483,26513,26775,26778,27087,27204,27467,27529
5,NaN,Antigua and Barbuda,17.06080,-61.796400,0,0,0,0,0,0,...,1182,1184,1188,1188,1192,1192,1200,1200,1200,1200
6,NaN,Argentina,-38.41610,-63.616700,0,0,0,0,0,0,...,2992325,3009150,3035134,3060145,3083298,3106949,3133183,3157660,3181288,3219474
7,NaN,Armenia,40.06910,45.038200,0,0,0,0,0,0,...,209222,209508,209980,210464,210835,211057,211375,211634,211957,212265
8,Australian Capital Territory,Australia,-35.47350,149.012400,0,0,0,0,0,0,...,121,121,121,121,121,121,121,121,121,121
9,New South Wales,Australia,-33.86880,151.209300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
latest_data = pd.read_csv('COVID-19-Dataset/csse_covid_19_data/csse_covid_19_daily_reports/04-28-2021.csv')

In [10]:
latest_data.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-04-29 04:20:55,33.93911,67.709953,59370,2611,52974.0,3785.0,Afghanistan,152.510994,4.397844
1,NaN,NaN,NaN,Albania,2021-04-29 04:20:55,41.15330,20.168300,130859,2386,107887.0,20586.0,Albania,4547.188825,1.823337
2,NaN,NaN,NaN,Algeria,2021-04-29 04:20:55,28.03390,1.659600,121580,3234,84745.0,33601.0,Algeria,277.256803,2.659977
3,NaN,NaN,NaN,Andorra,2021-04-29 04:20:55,42.50630,1.521800,13148,125,12590.0,433.0,Andorra,17016.760500,0.950715
4,NaN,NaN,NaN,Angola,2021-04-29 04:20:55,-11.20270,17.873900,26168,591,23584.0,1993.0,Angola,79.619627,2.258484

In [11]:
#Dataset: confirmed_cases, deaths_reported,  recovered_cases, latest_data

In [12]:
confirmed_cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Columns: 496 entries, Province/State to 5/27/21
dtypes: float64(2), int64(492), object(2)
memory usage: 1.0+ MB

In [13]:
deaths_reported.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Columns: 496 entries, Province/State to 5/27/21
dtypes: float64(2), int64(492), object(2)
memory usage: 1.0+ MB

In [14]:
recovered_cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Columns: 496 entries, Province/State to 5/27/21
dtypes: float64(2), int64(492), object(2)
memory usage: 1011.5+ KB

In [15]:
latest_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3984 entries, 0 to 3983
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   FIPS                 3266 non-null   float64
 1   Admin2               3271 non-null   object
 2   Province_State       3812 non-null   object
 3   Country_Region       3984 non-null   object
 4   Last_Update          3984 non-null   object
 5   Lat                  3896 non-null   float64
 6   Long_                3896 non-null   float64
 7   Confirmed            3984 non-null   int64
 8   Deaths               3984 non-null   int64
 9   Recovered            707 non-null    float64
 10  Active               706 non-null    float64
 11  Combined_Key         3984 non-null   object
 12  Incident_Rate        3896 non-null   float64
 13  Case_Fatality_Ratio  3944 non-null   float64
dtypes: float64(7), int64(2), object(5)
memory usage: 435.9+ KB

In [16]:
confirmed_cases.shape

(276, 496)

In [17]:
deaths_reported.shape

(276, 496)

In [18]:
recovered_cases.shape

(261, 496)

In [19]:
latest_data.shape

(3984, 14)

In [20]:
confirmed_cases.describe()

,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
count,274.000000,274.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,...,2.760000e+02,2.760000e+02,2.760000e+02,2.760000e+02,2.760000e+02,2.760000e+02,2.760000e+02,2.760000e+02,2.760000e+02,2.760000e+02
mean,20.447559,22.328281,2.018116,2.373188,3.409420,5.192029,7.673913,10.605072,20.210145,22.344203,...,5.950428e+05,5.974743e+05,5.984867e+05,6.007543e+05,6.028478e+05,6.045727e+05,6.062187e+05,6.081457e+05,6.101765e+05,6.121970e+05
std,25.189838,74.369096,26.781738,26.879567,33.464159,46.575328,65.089830,87.699030,215.201418,216.521511,...,2.775108e+06,2.787589e+06,2.797198e+06,2.808982e+06,2.819859e+06,2.828976e+06,2.837786e+06,2.847660e+06,2.857948e+06,2.867373e+06
min,-51.796300,-178.116500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,4.933349,-22.036550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.312000e+03,1.316000e+03,1.316250e+03,1.316250e+03,1.316250e+03,1.316250e+03,1.316250e+03,1.316250e+03,1.328250e+03,1.335000e+03
50%,21.607879,20.921188,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.867650e+04,1.868250e+04,1.869000e+04,1.888950e+04,1.897900e+04,1.899650e+04,1.901950e+04,1.904750e+04,1.907100e+04,1.909950e+04
75%,40.950592,83.380449,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.465390e+05,2.492698e+05,2.504960e+05,2.512458e+05,2.518208e+05,2.522262e+05,2.525150e+05,2.527770e+05,2.530820e+05,2.533535e+05
max,71.706900,178.065000,444.000000,444.000000,549.000000,761.000000,1058.000000,1423.000000,3554.000000,3554.000000,...,3.299733e+07,3.302662e+07,3.305676e+07,3.308511e+07,3.310488e+07,3.311774e+07,3.314366e+07,3.316642e+07,3.319047e+07,3.321800e+07

In [21]:
deaths_reported.describe()

,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
count,274.000000,274.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,...,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000,276.000000
mean,20.447559,22.328281,0.061594,0.065217,0.094203,0.152174,0.202899,0.297101,0.474638,0.481884,...,12334.851449,12383.199275,12429.489130,12475.775362,12516.884058,12551.492754,12583.463768,12629.666667,12675.518116,12721.753623
std,25.189838,74.369096,1.023280,1.024830,1.446690,2.408778,3.131446,4.575682,7.524221,7.524725,...,51933.913390,52131.806339,52329.281871,52520.048682,52688.611368,52822.293448,52944.604575,53139.770636,53349.206380,53566.287182
min,-51.796300,-178.116500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.933349,-22.036550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,8.750000,8.750000,8.750000,8.750000,8.750000,8.750000,8.750000,8.750000,8.750000,8.750000
50%,21.607879,20.921188,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,241.500000,242.000000,242.500000,244.500000,246.500000,254.000000,255.500000,258.000000,259.000000,261.000000
75%,40.950592,83.380449,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3472.250000,3485.250000,3486.000000,3489.750000,3495.750000,3495.750000,3505.000000,3512.500000,3515.500000,3517.250000
max,71.706900,178.065000,17.000000,17.000000,24.000000,40.000000,52.000000,76.000000,125.000000,125.000000,...,587300.000000,587955.000000,588620.000000,589223.000000,589703.000000,589893.000000,590320.000000,590941.000000,591950.000000,593288.000000

In [22]:
recovered_cases.describe()

,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
count,260.000000,260.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,...,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02
mean,19.016304,27.737245,0.114943,0.122605,0.149425,0.160920,0.214559,0.249042,0.413793,0.486590,...,3.852569e+05,3.879313e+05,3.903707e+05,3.927262e+05,3.950893e+05,3.970126e+05,3.994171e+05,4.016281e+05,4.037476e+05,4.064237e+05
std,24.632725,71.847810,1.737097,1.740995,1.932687,1.997346,2.631163,2.828979,4.985869,5.483964,...,1.723279e+06,1.744509e+06,1.763793e+06,1.782749e+06,1.801814e+06,1.817403e+06,1.835971e+06,1.852665e+06,1.868685e+06,1.887780e+06
min,-51.796300,-178.116500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,4.562000,-9.496274,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000e+03,1.000000e+03,1.002000e+03,1.003000e+03,1.025000e+03,1.039000e+03,1.039000e+03,1.039000e+03,1.039000e+03,1.039000e+03
50%,19.584785,24.242250,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.243700e+04,1.321800e+04,1.321800e+04,1.321800e+04,1.321800e+04,1.321800e+04,1.321800e+04,1.321800e+04,1.321800e+04,1.321800e+04
75%,38.991325,90.375625,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.826930e+05,1.836960e+05,1.843730e+05,1.852430e+05,1.862230e+05,1.866780e+05,1.874460e+05,1.876910e+05,1.885670e+05,1.894760e+05
max,71.706900,178.065000,28.000000,28.000000,31.000000,32.000000,42.000000,45.000000,80.000000,88.000000,...,2.198636e+07,2.235544e+07,2.271274e+07,2.307036e+07,2.342547e+07,2.372801e+07,2.405486e+07,2.435082e+07,2.463395e+07,2.489341e+07

In [23]:
latest_data.describe()

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active,Incident_Rate,Case_Fatality_Ratio
count,3266.000000,3896.000000,3896.000000,3.984000e+03,3984.000000,7.070000e+02,7.060000e+02,3896.000000,3944.000000
mean,32401.272811,35.975407,-72.060342,3.755594e+04,790.944277,1.228332e+05,3.962135e+04,8611.718801,2.042340
std,18033.806874,13.038331,53.675701,2.049521e+05,4447.213647,3.490168e+05,2.692251e+05,3914.838012,2.777815
min,66.000000,-52.368000,-178.116500,0.000000e+00,0.000000,0.000000e+00,-1.858844e+06,0.000000,0.000000
25%,19049.500000,33.268297,-96.618047,1.100750e+03,18.000000,6.170000e+02,3.982500e+02,6517.040192,1.212493
50%,30068.000000,37.949334,-86.859840,3.064000e+03,56.000000,1.703800e+04,3.317500e+03,9194.644840,1.775736
75%,47040.500000,42.222517,-77.494046,1.242175e+04,193.250000,7.633600e+04,2.583800e+04,11096.755562,2.487359
max,99999.000000,71.706900,178.065000,5.521227e+06,112134.000000,4.212461e+06,5.115685e+06,35747.684973,129.367631

In [24]:
# Fetching all the columns from confirmed dataset
cols = confirmed_cases.keys()
cols

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '5/18/21', '5/19/21', '5/20/21', '5/21/21', '5/22/21', '5/23/21',
       '5/24/21', '5/25/21', '5/26/21', '5/27/21'],
      dtype='object', length=496)

In [25]:
#Extracting the date columns
confirmed = confirmed_cases.loc[:, cols[4]:cols[-1]]
deaths = deaths_reported.loc[:, cols[4]:cols[-1]]
recoveries = recovered_cases.loc[:, cols[4]:cols[-1]]

In [26]:
confirmed

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
0,0,0,0,0,0,0,0,0,0,0,...,63819,64122,64575,65080,65486,65728,66275,66903,67743,68366
1,0,0,0,0,0,0,0,0,0,0,...,132071,132095,132118,132153,132176,132209,132215,132229,132244,132264
2,0,0,0,0,0,0,0,0,0,0,...,125693,125896,126156,126434,126651,126860,127107,127361,127646,127926
3,0,0,0,0,0,0,0,0,0,0,...,13569,13569,13569,13569,13569,13569,13569,13664,13671,13682
4,0,0,0,0,0,0,0,0,0,0,...,31045,31438,31661,31909,32149,32441,32623,32933,33338,33607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,0,2,2,2,2,2,2,2,2,2,...,4512,4720,4809,4941,5119,5275,5404,5931,6086,6356
272,0,0,0,0,0,0,0,0,0,0,...,304074,304532,304532,304968,305201,305201,305777,306334,306795,306795
273,0,0,0,0,0,0,0,0,0,0,...,6586,6593,6613,6632,6649,6658,6662,6670,6688,6696
274,0,0,0,0,0,0,0,0,0,0,...,92520,92630,92754,92920,93106,93201,93279,93428,93627,93947
275,0,0,0,0,0,0,0,0,0,0,...,38595,38612,38635,38664,38679,38682,38696,38706,38819,38854

In [27]:
deaths

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
0,0,0,0,0,0,0,0,0,0,0,...,2751,2762,2772,2782,2792,2802,2812,2836,2855,2869
1,0,0,0,0,0,0,0,0,0,0,...,2436,2438,2440,2441,2442,2444,2445,2447,2447,2447
2,0,0,0,0,0,0,0,0,0,0,...,3388,3395,3401,3405,3411,3418,3426,3433,3440,3448
3,0,0,0,0,0,0,0,0,0,0,...,127,127,127,127,127,127,127,127,127,127
4,0,0,0,0,0,0,0,0,0,0,...,685,696,704,709,715,725,731,735,742,745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,0,0,0,0,0,0,0,0,0,0,...,37,37,39,41,42,43,44,44,45,46
272,0,0,0,0,0,0,0,0,0,0,...,3437,3448,3448,3452,3459,3459,3470,3480,3483,3483
273,0,0,0,0,0,0,0,0,0,0,...,1297,1298,1301,1302,1304,1307,1310,1311,1313,1315
274,0,0,0,0,0,0,0,0,0,0,...,1263,1263,1265,1266,1267,1268,1271,1271,1273,1275
275,0,0,0,0,0,0,0,0,0,0,...,1583,1583,1585,1586,1586,1586,1586,1587,1589,1592

In [28]:
recoveries

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,5/18/21,5/19/21,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21
0,0,0,0,0,0,0,0,0,0,0,...,55118,55529,55687,55790,55889,56035,56295,56518,56711,56962
1,0,0,0,0,0,0,0,0,0,0,...,126405,127240,127869,128425,128601,128732,128826,128907,128978,129042
2,0,0,0,0,0,0,0,0,0,0,...,87609,87746,87902,88066,88208,88346,88497,88672,88861,89040
3,0,0,0,0,0,0,0,0,0,0,...,13234,13234,13234,13234,13234,13234,13234,13263,13381,13405
4,0,0,0,0,0,0,0,0,0,0,...,26013,26458,26483,26513,26775,26778,27087,27204,27467,27529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,0,0,0,0,0,0,0,0,0,0,...,2687,2687,2687,2689,2721,2721,2794,2794,2853,2853
257,0,0,0,0,0,0,0,0,0,0,...,293808,295643,295643,296901,297201,297201,298502,299024,299559,299559
258,0,0,0,0,0,0,0,0,0,0,...,3072,3120,3159,3179,3201,3245,3260,3273,3306,3339
259,0,0,0,0,0,0,0,0,0,0,...,90892,90919,90955,91019,91102,91156,91200,91221,91239,91321
260,0,0,0,0,0,0,0,0,0,0,...,36371,36416,36427,36435,36445,36453,36471,36517,36531,36541

In [29]:
#Range of date
dates = confirmed.keys()

#Summary
world_cases = []
total_deaths = [] 
mortality_rate = []
recovery_rate = [] 
total_recovered = [] 
total_active = [] 

#Confirmed
china_cases = [] 
italy_cases = []
us_cases = [] 
spain_cases = [] 
france_cases = [] 
germany_cases = [] 
uk_cases = [] 
russia_cases = []
india_cases = []

#Death
china_deaths = [] 
italy_deaths = []
us_deaths = [] 
spain_deaths = [] 
france_deaths = [] 
germany_deaths = [] 
uk_deaths = [] 
russia_deaths = []
india_deaths = []

#Recovered
china_recoveries = [] 
italy_recoveries = []
us_recoveries = [] 
spain_recoveries = [] 
france_recoveries = [] 
germany_recoveries = [] 
uk_recoveries = [] 
russia_recoveries = [] 
india_recoveries = []

In [30]:
dates

Index(['1/22/20', '1/23/20', '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       '1/28/20', '1/29/20', '1/30/20', '1/31/20',
       ...
       '5/18/21', '5/19/21', '5/20/21', '5/21/21', '5/22/21', '5/23/21',
       '5/24/21', '5/25/21', '5/26/21', '5/27/21'],
      dtype='object', length=492)

In [31]:
# Fill with the dataset
for i in dates:
    confirmed_sum = confirmed[i].sum()
    death_sum = deaths[i].sum()
    recovered_sum = recoveries[i].sum()
    
    world_cases.append(confirmed_sum)
    total_deaths.append(death_sum)
    total_recovered.append(recovered_sum)
    total_active.append(confirmed_sum-death_sum-recovered_sum)
    
    mortality_rate.append(death_sum/confirmed_sum)
    recovery_rate.append(recovered_sum/confirmed_sum)
    
    china_cases.append(confirmed_cases[confirmed_cases['Country/Region']=='China'][i].sum())
    italy_cases.append(confirmed_cases[confirmed_cases['Country/Region']=='Italy'][i].sum())
    us_cases.append(confirmed_cases[confirmed_cases['Country/Region']=='US'][i].sum())
    spain_cases.append(confirmed_cases[confirmed_cases['Country/Region']=='Spain'][i].sum())
    france_cases.append(confirmed_cases[confirmed_cases['Country/Region']=='France'][i].sum())
    germany_cases.append(confirmed_cases[confirmed_cases['Country/Region']=='Germany'][i].sum())
    uk_cases.append(confirmed_cases[confirmed_cases['Country/Region']=='United Kingdom'][i].sum())
    russia_cases.append(confirmed_cases[confirmed_cases['Country/Region']=='Russia'][i].sum())
    india_cases.append(confirmed_cases[confirmed_cases['Country/Region']=='India'][i].sum())
    
    china_deaths.append(deaths_reported[deaths_reported['Country/Region']=='China'][i].sum())
    italy_deaths.append(deaths_reported[deaths_reported['Country/Region']=='Italy'][i].sum())
    us_deaths.append(deaths_reported[deaths_reported['Country/Region']=='US'][i].sum())
    spain_deaths.append(deaths_reported[deaths_reported['Country/Region']=='Spain'][i].sum())
    france_deaths.append(deaths_reported[deaths_reported['Country/Region']=='France'][i].sum())
    germany_deaths.append(deaths_reported[deaths_reported['Country/Region']=='Germany'][i].sum())
    uk_deaths.append(deaths_reported[deaths_reported['Country/Region']=='United Kingdom'][i].sum())
    russia_deaths.append(deaths_reported[deaths_reported['Country/Region']=='Russia'][i].sum())
    india_deaths.append(deaths_reported[deaths_reported['Country/Region']=='India'][i].sum())
  
    china_recoveries.append(recovered_cases[recovered_cases['Country/Region']=='China'][i].sum())
    italy_recoveries.append(recovered_cases[recovered_cases['Country/Region']=='Italy'][i].sum())
    us_recoveries.append(recovered_cases[recovered_cases['Country/Region']=='US'][i].sum())
    spain_recoveries.append(recovered_cases[recovered_cases['Country/Region']=='Spain'][i].sum())
    france_recoveries.append(recovered_cases[recovered_cases['Country/Region']=='France'][i].sum())
    germany_recoveries.append(recovered_cases[recovered_cases['Country/Region']=='Germany'][i].sum())
    uk_recoveries.append(recovered_cases[recovered_cases['Country/Region']=='United Kingdom'][i].sum())
    russia_recoveries.append(recovered_cases[recovered_cases['Country/Region']=='Russia'][i].sum())
    india_recoveries.append(recovered_cases[recovered_cases['Country/Region']=='India'][i].sum())

In [32]:
world_cases

[557,
 655,
 941,
 1433,
 2118,
 2927,
 5578,
 6167,
 8235,
 9927,
 12038,
 16787,
 19887,
 23898,
 27643,
 30803,
 34396,
 37130,
 40160,
 42769,
 44811,
 45229,
 60382,
 66909,
 69052,
 71235,
 73270,
 75152,
 75652,
 76212,
 76841,
 78602,
 78982,
 79546,
 80399,
 81376,
 82736,
 84122,
 86013,
 88394,
 90377,
 92971,
 95279,
 98090,
 102003,
 106098,
 110047,
 114219,
 119041,
 126702,
 132492,
 146876,
 157950,
 169219,
 184027,
 199970,
 219535,
 246584,
 277359,
 309350,
 344205,
 387040,
 428219,
 479220,
 542097,
 607138,
 674418,
 733655,
 798949,
 875794,
 958602,
 1041662,
 1125221,
 1183584,
 1256176,
 1329331,
 1399162,
 1482540,
 1569554,
 1655088,
 1729371,
 1849067,
 1919809,
 2003820,
 2080934,
 2176465,
 2264462,
 2341702,
 2418307,
 2494325,
 2570074,
 2651321,
 2735570,
 2819666,
 2901925,
 2973513,
 3043705,
 3119245,
 3196355,
 3279850,
 3368226,
 3447426,
 3523799,
 3601488,
 3681990,
 3772018,
 3860724,
 3951003,
 4036226,
 4111202,
 4187833,
 4272324,
 4357304,
 4453535,
 4549267,
 4643706,
 4721728,
 4810895,
 4907670,
 5009548,
 5116192,
 5222614,
 5327418,
 5421629,
 5508346,
 5602313,
 5705075,
 5824358,
 5945261,
 6081776,
 6188184,
 6284179,
 6406143,
 6520392,
 6651336,
 6782559,
 6916296,
 7028659,
 7131156,
 7256216,
 7391321,
 7529341,
 7658106,
 7793395,
 7925679,
 8045337,
 8187421,
 8331167,
 8472230,
 8652145,
 8809593,
 8937295,
 9076656,
 9243465,
 9416059,
 9594440,
 9786037,
 9964169,
 10128040,
 10283387,
 10457929,
 10675536,
 10885481,
 11086866,
 11280675,
 11464678,
 11628653,
 11840015,
 12054174,
 12281001,
 12513675,
 12730157,
 12922431,
 13113875,
 13336063,
 13567531,
 13818843,
 14061585,
 14297763,
 14511197,
 14718313,
 14951994,
 15231862,
 15514716,
 15795790,
 16049844,
 16262880,
 16489410,
 16742195,
 17033923,
 17314023,
 17604767,
 17853105,
 18084097,
 18290572,
 18548514,
 18825089,
 19110291,
 19392530,
 19651048,
 19875731,
 20101760,
 20359330,
 20635977,
 20925193,
 21228941,
 21476649,
 21691119,
 21898851,
 22157107,
 22436697,
 22709251,
 22970456,
 23234707,
 23440856,
 23666124,
 23910125,
 24193918,
 24477813,
 24761440,
 25025233,
 25246198,
 25509089,
 25774014,
 26057518,
 26338937,
 26652953,
 26922944,
 27153409,
 27371291,
 27613490,
 27898312,
 28198188,
 28519558,
 28806136,
 29048855,
 29312607,
 29598069,
 29902604,
 30217490,
 30543411,
 30835530,
 31087644,
 31363730,
 31648244,
 31924336,
 32277373,
 32608243,
 32896685,
 33148076,
 33402856,
 33685524,
 34011734,
 34330037,
 34627903,
 34959947,
 35221344,
 35522367,
 35848886,
 36199883,
 36561210,
 36922107,
 37279208,
 37566120,
 37857886,
 38177145,
 38559479,
 38966463,
 39378234,
 39750891,
 40067454,
 40454664,
 40843666,
 41288556,
 41761275,
 42258073,
 42714857,
 43075510,
 43561921,
 44032154,
 44544026,
 45094441,
 45665496,
 46142261,
 46604645,
 47167772,
 47721517,
 48233069,
 48829627,
 49474481,
 50071373,
 50555347,
 51056879,
 51616256,
 52264862,
 52914405,
 53566478,
 54161448,
 54635389,
 55169846,
 55781066,
 56408169,
 57061754,
 57730498,
 58318062,
 58806043,
 59331362,
 59921623,
 60557847,
 61140322,
 61827470,
 62413501,
 62902084,
 63410725,
 64022822,
 64674220,
 65368548,
 66051824,
 66693987,
 67232741,
 67752760,
 68396288,
 69066199,
 70564412,
 71268909,
 71903759,
 72434597,
 72959984,
 73596190,
 74329916,
 75069498,
 75789960,
 76401213,
 76934686,
 77483983,
 78134244,
 78829366,
 79496006,
 79961556,
 80474158,
 80912611,
 81408934,
 82073362,
 82834592,
 83559601,
 84092619,
 84718978,
 85251774,
 85805892,
 86546014,
 87329386,
 88210223,
 89013445,
 89774439,
 90363573,
 90983503,
 91689011,
 92437399,
 93192627,
 93959814,
 94598958,
 95128170,
 95643236,
 96251662,
 96944599,
 97600922,
 98259983,
 98828107,
 99273761,
 99771101,
 100327339,
 100925700,
 101539951,
 102130394,
 102645724,
 103027363,
 103474137,
 103932094,
 104454075,
 104920982,
 105456410,
 105828535,
 106226613,
 106542506,
 106970539,
 107406280,
 107847745,
 108276434,
 108649735,
 108943585,
 109226751,
 109577771,
 109973326,
 110376842,
 110789361,
 111159816,
 111474262,
 111762700,
 112151553,
 112596489,
 113043967,
 113487006,
 113876236,
 114179745,
 114485609,
 114795897,
 115237039,
 115690088,
 116137142,
 116547675,
 116915987,
 117214710,
 117629375,
 118096454,
 118573350,
 119062678,
 119516794,
 119877179,
 120226080,
 120699093,
 121238378,
 121792101,
 122353780,
 122852600,
 123275915,
 123692736,
 124206981,
 124840562,
 125491912,
 126133263,
 126717855,
 127187813,
 127646218,
 128214491,
 128897696,
 129609483,
 130243222,
 130772665,
 131325468,
 131815052,
 132419139,
 133103485,
 133943335,
 134691380,
 135355887,
 136046628,
 136663253,
 137442820,
 138259845,
 139076606,
 139931461,
 140719503,
 141404998,
 142098420,
 142952845,
 143842820,
 144742575,
 145646322,
 146467262,
 147189618,
 147872402,
 148716872,
 149622864,
 150520466,
 151399480,
 152196159,
 152870507,
 153552097,
 154359533,
 155200757,
 156070729,
 156902287,
 157688833,
 158330372,
 158952301,
 159690774,
 160450873,
 161176148,
 161894208,
 162521726,
 163069932,
 163609626,
 164231811,
 164902903,
 165182316,
 165808192,
 166385987,
 166862062,
 167316362,
 167848207,
 168408716,
 168966369]

In [33]:
total_deaths

[17,
 18,
 26,
 42,
 56,
 82,
 131,
 133,
 171,
 213,
 259,
 362,
 426,
 492,
 564,
 634,
 719,
 806,
 906,
 1013,
 1113,
 1118,
 1371,
 1523,
 1666,
 1770,
 1868,
 2008,
 2123,
 2248,
 2252,
 2459,
 2470,
 2630,
 2710,
 2771,
 2814,
 2873,
 2942,
 2996,
 3085,
 3160,
 3255,
 3349,
 3460,
 3564,
 3803,
 3993,
 4267,
 4611,
 4917,
 5414,
 5834,
 6475,
 7153,
 7967,
 8874,
 9985,
 11470,
 13192,
 14878,
 16827,
 19117,
 21927,
 24962,
 28450,
 32180,
 35699,
 39780,
 44528,
 50526,
 56413,
 62574,
 68488,
 73676,
 79614,
 87872,
 94683,
 102467,
 109845,
 116017,
 121876,
 127842,
 134812,
 143285,
 150544,
 158938,
 165083,
 170316,
 176188,
 183461,
 190325,
 197153,
 203923,
 209551,
 213530,
 218276,
 224854,
 231579,
 237421,
 242572,
 248067,
 251578,
 255791,
 261614,
 268119,
 273429,
 278981,
 283206,
 286765,
 290251,
 295736,
 300868,
 306037,
 311258,
 315434,
 318621,
 322384,
 327031,
 331810,
 336469,
 341713,
 345640,
 348656,
 349868,
 354110,
 359166,
 363718,
 368326,
 372350,
 375042,
 378115,
 382792,
 388224,
 393258,
 397836,
 401605,
 404345,
 408047,
 412821,
 417864,
 422504,
 426713,
 430829,
 434229,
 437645,
 444355,
 449502,
 454412,
 460478,
 464587,
 468601,
 472163,
 477380,
 482555,
 487247,
 491995,
 496458,
 499624,
 503302,
 508187,
 513132,
 518207,
 523134,
 527538,
 531027,
 534872,
 540839,
 546114,
 551521,
 556820,
 561638,
 565625,
 569536,
 575133,
 580579,
 586351,
 593019,
 598616,
 602700,
 606911,
 613080,
 620026,
 629914,
 635944,
 641513,
 645226,
 650409,
 656674,
 663281,
 669331,
 675517,
 680972,
 685298,
 689984,
 696514,
 703565,
 710056,
 716344,
 721758,
 726331,
 731683,
 737882,
 744450,
 750664,
 760803,
 766159,
 770423,
 774604,
 781411,
 788138,
 794210,
 799648,
 805146,
 809100,
 813606,
 819892,
 826118,
 832014,
 837543,
 842865,
 846910,
 851087,
 857486,
 863595,
 869279,
 875148,
 880088,
 883934,
 893308,
 898221,
 904326,
 910130,
 915981,
 920862,
 924577,
 929017,
 935443,
 941223,
 946691,
 952359,
 957638,
 961377,
 965479,
 971451,
 977061,
 983715,
 989618,
 994963,
 998650,
 1002625,
 1008528,
 1014992,
 1023707,
 1028643,
 1034007,
 1037846,
 1044792,
 1050568,
 1056404,
 1062682,
 1068832,
 1073714,
 1077747,
 1081730,
 1087016,
 1093089,
 1099204,
 1105389,
 1110986,
 1114528,
 1119364,
 1125918,
 1132548,
 1138483,
 1145454,
 1151271,
 1155482,
 1160999,
 1168371,
 1175531,
 1182617,
 1190216,
 1196794,
 1201804,
 1207908,
 1217253,
 1227504,
 1235518,
 1245179,
 1252779,
 1258654,
 1265877,
 1275870,
 1286321,
 1296087,
 1305675,
 1314757,
 1321182,
 1329136,
 1340207,
 1351621,
 1362654,
 1374541,
 1383513,
 1390708,
 1399234,
 1411894,
 1424025,
 1434913,
 1446300,
 1455583,
 1462743,
 1471623,
 1484309,
 1496898,
 1509473,
 1521993,
 1532282,
 1539710,
 1548425,
 1560705,
 1573425,
 1586121,
 1599149,
 1609694,
 1617153,
 1626325,
 1640278,
 1653937,
 1667388,
 1680178,
 1690950,
 1698865,
 1708512,
 1722825,
 1736628,
 1748259,
 1756861,
 1764260,
 1771659,
 1781415,
 1796581,
 1811843,
 1825012,
 1834675,
 1843108,
 1850449,
 1860598,
 1875933,
 1890986,
 1905926,
 1921092,
 1933877,
 1942225,
 1952549,
 1969653,
 1986359,
 2001730,
 2016841,
 2030089,
 2038753,
 2048179,
 2064762,
 2082668,
 2099457,
 2115478,
 2128772,
 2137740,
 2148508,
 2165816,
 2182496,
 2199547,
 2214494,
 2228080,
 2236070,
 2246288,
 2261124,
 2276852,
 2289386,
 2305957,
 2316094,
 2324080,
 2332412,
 2347949,
 2361352,
 2374826,
 2387299,
 2397104,
 2403466,
 2410360,
 2421278,
 2432617,
 2443987,
 2455035,
 2463547,
 2469427,
 2476376,
 2487556,
 2499559,
 2509724,
 2519974,
 2528114,
 2533548,
 2540757,
 2551191,
 2562264,
 2572042,
 2582059,
 2589891,
 2595165,
 2602025,
 2612006,
 2621697,
 2631464,
 2641092,
 2649078,
 2654577,
 2661398,
 2671288,
 2681413,
 2691987,
 2702386,
 2710432,
 2716233,
 2723729,
 2734835,
 2744557,
 2755896,
 2768118,
 2777955,
 2784435,
 2792398,
 2803971,
 2816248,
 2828123,
 2838382,
 2846779,
 2853709,
 2861183,
 2873010,
 2887858,
 2902512,
 2915934,
 2928349,
 2936924,
 2946232,
 2959574,
 2973125,
 2986338,
 2999175,
 3011198,
 3019823,
 3030332,
 3044533,
 3058651,
 3072396,
 3086756,
 3100051,
 3109724,
 3120896,
 3135393,
 3151122,
 3166125,
 3180403,
 3192977,
 3202930,
 3214016,
 3227921,
 3242126,
 3256371,
 3270109,
 3283286,
 3293188,
 3303957,
 3317579,
 3331516,
 3344655,
 3357785,
 3369435,
 3379526,
 3390170,
 3404419,
 3417763,
 3430539,
 3443314,
 3454660,
 3464212,
 3473036,
 3485788,
 3498443,
 3511204]

In [34]:
confirmed_sum

168966369

In [35]:
death_sum

3511204

In [36]:
recovered_sum

106076597

In [37]:
china_cases

[548,
 643,
 920,
 1406,
 2075,
 2877,
 5509,
 6087,
 8141,
 9802,
 11891,
 16630,
 19716,
 23707,
 27440,
 30587,
 34110,
 36814,
 39829,
 42354,
 44386,
 44759,
 59895,
 66358,
 68413,
 70513,
 72434,
 74211,
 74619,
 75077,
 75550,
 77001,
 77022,
 77241,
 77754,
 78166,
 78600,
 78928,
 79356,
 79932,
 80136,
 80261,
 80386,
 80537,
 80690,
 80770,
 80823,
 80860,
 80887,
 80921,
 80932,
 80945,
 80977,
 81003,
 81033,
 81058,
 81102,
 81156,
 81250,
 81305,
 81435,
 81498,
 81591,
 81661,
 81782,
 81897,
 81999,
 82122,
 82198,
 82279,
 82361,
 82432,
 82511,
 82543,
 82602,
 82665,
 82718,
 82809,
 82883,
 82941,
 83014,
 83134,
 83213,
 83306,
 83356,
 83403,
 83760,
 83787,
 83805,
 83817,
 83853,
 83868,
 83884,
 83899,
 83909,
 83912,
 83918,
 83940,
 83944,
 83956,
 83959,
 83959,
 83964,
 83966,
 83968,
 83970,
 83975,
 83976,
 83990,
 84010,
 84011,
 84018,
 84024,
 84029,
 84038,
 84044,
 84054,
 84063,
 84063,
 84063,
 84063,
 84081,
 84084,
 84095,
 84102,
 84103,
 84106,
 84106,
 84123,
 84128,
 84146,
 84154,
 84161,
 84160,
 84171,
 84177,
 84186,
 84191,
 84195,
 84198,
 84209,
 84216,
 84228,
 84286,
 84335,
 84378,
 84422,
 84458,
 84494,
 84494,
 84553,
 84572,
 84624,
 84653,
 84673,
 84701,
 84725,
 84743,
 84757,
 84780,
 84785,
 84816,
 84830,
 84838,
 84857,
 84871,
 84889,
 84917,
 84950,
 84992,
 84992,
 85071,
 85117,
 85117,
 85226,
 85246,
 85327,
 85402,
 85418,
 85503,
 85622,
 85708,
 85906,
 86045,
 86202,
 86381,
 86570,
 86783,
 86990,
 87213,
 87489,
 87655,
 87827,
 87985,
 88099,
 88206,
 88328,
 88460,
 88580,
 88672,
 88793,
 88906,
 88958,
 89045,
 89144,
 89214,
 89279,
 89375,
 89441,
 89494,
 89527,
 89567,
 89616,
 89654,
 89695,
 89718,
 89752,
 89784,
 89814,
 89836,
 89863,
 89895,
 89914,
 89933,
 89953,
 89986,
 90008,
 90025,
 90058,
 90078,
 90087,
 90100,
 90127,
 90145,
 90168,
 90197,
 90219,
 90235,
 90253,
 90294,
 90311,
 90334,
 90369,
 90381,
 90399,
 90409,
 90424,
 90441,
 90456,
 90483,
 90505,
 90528,
 90545,
 90567,
 90584,
 90604,
 90629,
 90652,
 90667,
 90687,
 90728,
 90751,
 90778,
 90812,
 90830,
 90858,
 90869,
 90905,
 90925,
 90955,
 90972,
 91006,
 91022,
 91044,
 91073,
 91108,
 91128,
 91151,
 91175,
 91222,
 91271,
 91299,
 91339,
 91366,
 91397,
 91452,
 91478,
 91509,
 91552,
 91591,
 91622,
 91665,
 91693,
 91719,
 91752,
 91783,
 91807,
 91828,
 91850,
 91872,
 91885,
 91906,
 91935,
 91977,
 92037,
 92116,
 92211,
 92296,
 92402,
 92488,
 92586,
 92681,
 92814,
 92902,
 92993,
 93113,
 93221,
 93348,
 93467,
 93577,
 93670,
 93782,
 93898,
 94025,
 94124,
 94217,
 94328,
 94427,
 94537,
 94626,
 94734,
 94821,
 94953,
 95050,
 95150,
 95228,
 95298,
 95383,
 95460,
 95541,
 95632,
 95720,
 95797,
 95876,
 95963,
 96023,
 96086,
 96160,
 96246,
 96310,
 96398,
 96484,
 96562,
 96690,
 96824,
 96920,
 97095,
 97275,
 97448,
 97616,
 97775,
 97939,
 98164,
 98323,
 98544,
 98786,
 98886,
 99047,
 99247,
 99402,
 99541,
 99655,
 99746,
 99848,
 99968,
 100063,
 100127,
 100177,
 100226,
 100268,
 100318,
 100348,
 100389,
 100435,
 100475,
 100494,
 100527,
 100559,
 100578,
 100599,
 100624,
 100639,
 100666,
 100684,
 100705,
 100727,
 100758,
 100784,
 100808,
 100832,
 100851,
 100885,
 100924,
 100965,
 100990,
 101013,
 101037,
 101055,
 101076,
 101097,
 101132,
 101149,
 101175,
 101194,
 101225,
 101292,
 101349,
 101378,
 101421,
 101443,
 101460,
 101481,
 101498,
 101518,
 101533,
 101560,
 101582,
 101603,
 101623,
 101646,
 101663,
 101676,
 101692,
 101710,
 101732,
 101754,
 101799,
 101821,
 101861,
 101901,
 101920,
 101953,
 101984,
 102012,
 102027,
 102056,
 102078,
 102103,
 102118,
 102135,
 102167,
 102201,
 102242,
 102264,
 102293,
 102300,
 102333,
 102351,
 102367,
 102384,
 102399,
 102419,
 102446,
 102474,
 102494,
 102517,
 102530,
 102549,
 102560,
 102571,
 102586,
 102596,
 102613,
 102625,
 102643,
 102660,
 102671,
 102681,
 102696,
 102717,
 102746,
 102769,
 102784,
 102797,
 102822,
 102833,
 102853,
 102873,
 102890,
 102905,
 102925,
 102932]

In [38]:
italy_cases

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 20,
 62,
 155,
 229,
 322,
 453,
 655,
 888,
 1128,
 1694,
 2036,
 2502,
 3089,
 3858,
 4636,
 5883,
 7375,
 9172,
 10149,
 12462,
 15113,
 17660,
 21157,
 24747,
 27980,
 31506,
 35713,
 41035,
 47021,
 53578,
 59138,
 63927,
 69176,
 74386,
 80589,
 86498,
 92472,
 97689,
 101739,
 105792,
 110574,
 115242,
 119827,
 124632,
 128948,
 132547,
 135586,
 139422,
 143626,
 147577,
 152271,
 156363,
 159516,
 162488,
 165155,
 168941,
 172434,
 175925,
 178972,
 181228,
 183957,
 187327,
 189973,
 192994,
 195351,
 197675,
 199414,
 201505,
 203591,
 205463,
 207428,
 209328,
 210717,
 211938,
 213013,
 214457,
 215858,
 217185,
 218268,
 219070,
 219814,
 221216,
 222104,
 223096,
 223885,
 224760,
 225435,
 225886,
 226699,
 227364,
 228006,
 228658,
 229327,
 229858,
 230158,
 230555,
 231139,
 231732,
 232248,
 232664,
 232997,
 233197,
 233515,
 233836,
 234013,
 234531,
 234801,
 234998,
 235278,
 235561,
 235763,
 236142,
 236305,
 236651,
 236989,
 237290,
 237500,
 237828,
 238159,
 238011,
 238275,
 238499,
 238720,
 238833,
 239410,
 239706,
 239961,
 240136,
 240310,
 240436,
 240578,
 240760,
 240961,
 241184,
 241419,
 241611,
 241819,
 241956,
 242149,
 242363,
 242639,
 242827,
 243061,
 243230,
 243344,
 243506,
 243736,
 243967,
 244216,
 244434,
 244624,
 244752,
 245032,
 245338,
 245590,
 245864,
 246118,
 246286,
 246488,
 246776,
 247158,
 247537,
 247832,
 248070,
 248229,
 248419,
 248803,
 249204,
 249756,
 250103,
 250566,
 250825,
 251237,
 251713,
 252235,
 252809,
 253438,
 253915,
 254235,
 254636,
 255278,
 256118,
 257065,
 258136,
 259345,
 260298,
 261174,
 262540,
 263949,
 265409,
 266853,
 268218,
 269214,
 270189,
 271515,
 272912,
 274644,
 276338,
 277634,
 278784,
 280153,
 281583,
 283180,
 284796,
 286297,
 287753,
 288761,
 289990,
 291442,
 293025,
 294932,
 296569,
 298156,
 299506,
 300897,
 302537,
 304323,
 306235,
 308104,
 309870,
 311364,
 313011,
 314861,
 317409,
 319908,
 322751,
 325329,
 327586,
 330263,
 333940,
 338398,
 343770,
 349494,
 354950,
 359569,
 365467,
 372799,
 381602,
 391611,
 402536,
 414241,
 423578,
 434449,
 449648,
 465726,
 484869,
 504509,
 525782,
 542789,
 564778,
 589766,
 616595,
 647674,
 679430,
 709335,
 731588,
 759829,
 790377,
 824879,
 862681,
 902490,
 935104,
 960373,
 995463,
 1028424,
 1066401,
 1107303,
 1144552,
 1178529,
 1205881,
 1238072,
 1272352,
 1308528,
 1345767,
 1380531,
 1408868,
 1431795,
 1455022,
 1480874,
 1509875,
 1538217,
 1564532,
 1585178,
 1601554,
 1620901,
 1641610,
 1664829,
 1688939,
 1709991,
 1728878,
 1742557,
 1757394,
 1770149,
 1787147,
 1805873,
 1825775,
 1843712,
 1855737,
 1870576,
 1888144,
 1906377,
 1921778,
 1938083,
 1953185,
 1964054,
 1977370,
 1991278,
 2009317,
 2028354,
 2038759,
 2047696,
 2056277,
 2067487,
 2083689,
 2107166,
 2129376,
 2141201,
 2155446,
 2166244,
 2181619,
 2201945,
 2220361,
 2237890,
 2257866,
 2276491,
 2289021,
 2303263,
 2319036,
 2336279,
 2352423,
 2368733,
 2381277,
 2390102,
 2400598,
 2414166,
 2428221,
 2441854,
 2455185,
 2466813,
 2475372,
 2485956,
 2501147,
 2515507,
 2529070,
 2541783,
 2553032,
 2560957,
 2570608,
 2583790,
 2597446,
 2611659,
 2625098,
 2636738,
 2644707,
 2655319,
 2668266,
 2683403,
 2697296,
 2710819,
 2721879,
 2729223,
 2739591,
 2751657,
 2765412,
 2780882,
 2795796,
 2809246,
 2818863,
 2832162,
 2848564,
 2868435,
 2888923,
 2907825,
 2925265,
 2938371,
 2955434,
 2976274,
 2999119,
 3023129,
 3046762,
 3067486,
 3081368,
 3101093,
 3123368,
 3149017,
 3175807,
 3201838,
 3223142,
 3238394,
 3258770,
 3281810,
 3306711,
 3332418,
 3356331,
 3376376,
 3400877,
 3419616,
 3440862,
 3464543,
 3488619,
 3512453,
 3532057,
 3544957,
 3561012,
 3584899,
 3607083,
 3629000,
 3650247,
 3668264,
 3678944,
 3686707,
 3700393,
 3717602,
 3736526,
 3754077,
 3769814,
 3779594,
 3793033,
 3809193,
 3826156,
 3842079,
 3857443,
 3870131,
 3878994,
 3891063,
 3904899,
 3920945,
 3935703,
 3949517,
 3962674,
 3971114,
 3981512,
 3994894,
 4009208,
 4022653,
 4035617,
 4044762,
 4050708,
 4059821,
 4070400,
 4082198,
 4092747,
 4102921,
 4111210,
 4116287,
 4123230,
 4131078,
 4139160,
 4146722,
 4153374,
 4159122,
 4162576,
 4167025,
 4172525,
 4178261,
 4183476,
 4188190,
 4192183,
 4194672,
 4197892,
 4201827,
 4205970]

In [39]:
us_cases

[1,
 1,
 2,
 2,
 5,
 5,
 5,
 6,
 6,
 8,
 8,
 8,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 16,
 16,
 16,
 16,
 16,
 16,
 17,
 17,
 25,
 32,
 55,
 74,
 107,
 184,
 237,
 403,
 519,
 594,
 782,
 1147,
 1586,
 2219,
 2978,
 3212,
 4679,
 6512,
 9169,
 13663,
 20030,
 26025,
 34898,
 46136,
 56755,
 68837,
 86693,
 105383,
 125013,
 143912,
 165987,
 192301,
 224560,
 256792,
 289087,
 321477,
 351354,
 382747,
 413516,
 444731,
 480667,
 515081,
 544183,
 571440,
 598380,
 627205,
 652611,
 682626,
 715656,
 743588,
 769684,
 799512,
 825429,
 854288,
 887858,
 920185,
 950581,
 977082,
 1000785,
 1025362,
 1051800,
 1081020,
 1115946,
 1143296,
 1167593,
 1191678,
 1216209,
 1240769,
 1268180,
 1295019,
 1320155,
 1339022,
 1358293,
 1381241,
 1401649,
 1428467,
 1453214,
 1477373,
 1495736,
 1518126,
 1539133,
 1561830,
 1587596,
 1611253,
 1632364,
 1652431,
 1671104,
 1690754,
 1709303,
 1731625,
 1756098,
 1779731,
 1798718,
 1816154,
 1837656,
 1857511,
 1879150,
 1904550,
 1925710,
 1943626,
 1961263,
 1979647,
 2000757,
 2023890,
 2048756,
 2073964,
 2092912,
 2112731,
 2136401,
 2163465,
 2191991,
 2223553,
 2255823,
 2280971,
 2313123,
 2350198,
 2386074,
 2426391,
 2472385,
 2513731,
 2554461,
 2595744,
 2642174,
 2693993,
 2750622,
 2801983,
 2847664,
 2898432,
 2941517,
 3002171,
 3062290,
 3124786,
 3192841,
 3252874,
 3311312,
 3370208,
 3438244,
 3506364,
 3582184,
 3654445,
 3716980,
 3777456,
 3839546,
 3904066,
 3974630,
 4043070,
 4116393,
 4181308,
 4236083,
 4292934,
 4359391,
 4431244,
 4498701,
 4567420,
 4623604,
 4669149,
 4714678,
 4773479,
 4827936,
 4887293,
 4946590,
 5000709,
 5046463,
 5094087,
 5142088,
 5198137,
 5249451,
 5314791,
 5361712,
 5400904,
 5437580,
 5482614,
 5529973,
 5574013,
 5622842,
 5665887,
 5700119,
 5736641,
 5777001,
 5822167,
 5867547,
 5914395,
 5957126,
 5991507,
 6026895,
 6068759,
 6109773,
 6153983,
 6204376,
 6247464,
 6278633,
 6302200,
 6329593,
 6363650,
 6399723,
 6447501,
 6488563,
 6522914,
 6557342,
 6596849,
 6635867,
 6681004,
 6730288,
 6772447,
 6810862,
 6862834,
 6902696,
 6941758,
 6988869,
 7037151,
 7081803,
 7119311,
 7152546,
 7195994,
 7235428,
 7281081,
 7336043,
 7384578,
 7420293,
 7459742,
 7504998,
 7556060,
 7614653,
 7671034,
 7725952,
 7771893,
 7813735,
 7865983,
 7925748,
 7990636,
 8059782,
 8116518,
 8165858,
 8233610,
 8295581,
 8358864,
 8435164,
 8517113,
 8599842,
 8661982,
 8729385,
 8806228,
 8885632,
 8976684,
 9075924,
 9165619,
 9270467,
 9355775,
 9482891,
 9587499,
 9716853,
 9844858,
 9972308,
 10087380,
 10207953,
 10348449,
 10495075,
 10659914,
 10840303,
 11008064,
 11144288,
 11307233,
 11471155,
 11644332,
 11835880,
 12034177,
 12213451,
 12360235,
 12534684,
 12710198,
 12893485,
 13005807,
 13213995,
 13369528,
 13509762,
 13670332,
 13858551,
 14061108,
 14284721,
 14517506,
 14733048,
 14914060,
 15108918,
 15333410,
 15555949,
 15787464,
 16027441,
 16245026,
 16432729,
 16627550,
 16836556,
 17083256,
 17322981,
 17574950,
 17766856,
 17954675,
 18153724,
 18351735,
 18581353,
 18775557,
 18873203,
 19099491,
 19255126,
 19429760,
 19630012,
 19863696,
 20099363,
 20252991,
 20553301,
 20762047,
 20946329,
 21181440,
 21436884,
 21715174,
 22010389,
 22271084,
 22484332,
 22699326,
 22926246,
 23156608,
 23392315,
 23635046,
 23836726,
 24014508,
 24157924,
 24334630,
 24517866,
 24711684,
 24902437,
 25073050,
 25204112,
 25356081,
 25503621,
 25657566,
 25826176,
 25992744,
 26135056,
 26247053,
 26382255,
 26497588,
 26619229,
 26743204,
 26877601,
 26981588,
 27071236,
 27161551,
 27257183,
 27352360,
 27458120,
 27557758,
 27644880,
 27709901,
 27764087,
 27826806,
 27896924,
 27966848,
 28046145,
 28117670,
 28174750,
 28230970,
 28303233,
 28377965,
 28455466,
 28532812,
 28597387,
 28648744,
 28706973,
 28764033,
 28831226,
 28899277,
 28965728,
 29023931,
 29064938,
 29109974,
 29167616,
 29225536,
 29288010,
 29349533,
 29402465,
 29440686,
 29497352,
 29551309,
 29610445,
 29670983,
 29732612,
 29787986,
 29821754,
 29873347,
 29926950,
 30013910,
 30081375,
 30158696,
 30221396,
 30264493,
 30333922,
 30395171,
 30462210,
 30541255,
 30611086,
 30674153,
 30709125,
 30786804,
 30847348,
 30922386,
 31002264,
 31084962,
 31151497,
 31197877,
 31268107,
 31345985,
 31421360,
 31495649,
 31575640,
 31628013,
 31670031,
 31737964,
 31799237,
 31862094,
 31929351,
 31991750,
 32045113,
 32077178,
 32124869,
 32175725,
 32230850,
 32289049,
 32346971,
 32392274,
 32421641,
 32472201,
 32512934,
 32557669,
 32605183,
 32652472,
 32686965,
 32708357,
 32745255,
 32778906,
 32814784,
 32852871,
 32895169,
 32923982,
 32940846,
 32969512,
 32997331,
 33026624,
 33056765,
 33085106,
 33104884,
 33117737,
 33143662,
 33166418,
 33190470,
 33217995]

In [40]:
spain_cases

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 6,
 13,
 15,
 32,
 45,
 84,
 120,
 165,
 222,
 259,
 400,
 500,
 673,
 1073,
 1695,
 2277,
 2277,
 5232,
 6391,
 7798,
 9942,
 11748,
 13910,
 17963,
 20410,
 25374,
 28768,
 35136,
 39885,
 49515,
 57786,
 65719,
 73235,
 80110,
 87956,
 95923,
 104118,
 112065,
 119199,
 126168,
 131646,
 136675,
 141942,
 148220,
 153222,
 158273,
 163027,
 166831,
 170099,
 172541,
 177644,
 184948,
 190839,
 191726,
 198674,
 200210,
 204178,
 208389,
 213024,
 202990,
 205905,
 207634,
 209465,
 210773,
 212917,
 213435,
 215216,
 216582,
 217466,
 218011,
 219329,
 220325,
 221447,
 222857,
 223578,
 224350,
 227436,
 228030,
 228691,
 229540,
 230183,
 230698,
 230698,
 231606,
 232037,
 232555,
 233037,
 234824,
 235290,
 235772,
 235400,
 236259,
 236259,
 237906,
 238564,
 239228,
 239479,
 239638,
 239932,
 240326,
 240660,
 240978,
 241310,
 241550,
 241717,
 241966,
 242280,
 242707,
 243209,
 243605,
 243928,
 244109,
 244328,
 244683,
 245268,
 245575,
 245938,
 246272,
 246504,
 246752,
 247086,
 247486,
 247905,
 248469,
 248770,
 248970,
 249271,
 249659,
 250103,
 250545,
 250545,
 250545,
 251789,
 252130,
 252513,
 253056,
 253908,
 253908,
 253908,
 255953,
 256619,
 257494,
 258855,
 260255,
 260255,
 260255,
 264836,
 266194,
 267551,
 270166,
 272421,
 272421,
 272421,
 278782,
 280610,
 282641,
 285430,
 288522,
 288522,
 288522,
 297054,
 302814,
 305767,
 309855,
 314362,
 314362,
 314362,
 322980,
 326612,
 329784,
 337334,
 342813,
 342813,
 342813,
 359082,
 364196,
 370867,
 377906,
 386054,
 386054,
 386054,
 405436,
 412553,
 419849,
 429507,
 439286,
 439286,
 439286,
 462858,
 470973,
 479554,
 488513,
 498989,
 498989,
 498989,
 525549,
 534513,
 543379,
 554143,
 566326,
 566326,
 566326,
 593730,
 603167,
 614360,
 625651,
 640040,
 640040,
 640040,
 671468,
 682267,
 693556,
 704209,
 716481,
 716481,
 716481,
 748266,
 748266,
 769188,
 778607,
 789932,
 789932,
 789932,
 813412,
 825410,
 835901,
 848324,
 861112,
 861112,
 861112,
 888968,
 896086,
 908056,
 921374,
 936560,
 936560,
 936560,
 974449,
 988322,
 1005295,
 1026281,
 1046132,
 1046132,
 1046132,
 1098320,
 1116738,
 1136503,
 1160083,
 1185678,
 1185678,
 1185678,
 1240697,
 1259366,
 1284408,
 1306316,
 1328832,
 1328832,
 1328832,
 1381218,
 1381218,
 1417709,
 1437220,
 1458591,
 1458591,
 1458591,
 1496864,
 1510023,
 1525341,
 1541574,
 1556730,
 1556730,
 1556730,
 1582616,
 1594844,
 1605066,
 1617355,
 1628208,
 1628208,
 1628208,
 1648187,
 1656444,
 1665775,
 1675902,
 1684647,
 1684647,
 1684647,
 1702328,
 1702328,
 1712101,
 1720056,
 1730575,
 1730575,
 1730575,
 1751884,
 1762212,
 1773290,
 1785421,
 1797236,
 1797236,
 1797236,
 1819249,
 1829903,
 1842289,
 1854951,
 1854951,
 1854951,
 1854951,
 1879413,
 1893502,
 1910218,
 1928265,
 1928265,
 1928265,
 1928265,
 1958844,
 1982544,
 1982544,
 2024904,
 2050360,
 2050360,
 2050360,
 2111782,
 2137220,
 2176089,
 2211967,
 2252164,
 2252164,
 2252164,
 2336451,
 2370742,
 2412318,
 2456675,
 2499560,
 2499560,
 2499560,
 2593382,
 2629817,
 2670102,
 2705001,
 2743119,
 2743119,
 2743119,
 2822805,
 2851869,
 2883465,
 2913425,
 2941990,
 2941990,
 2941990,
 2989085,
 3005487,
 3023601,
 3041454,
 3056035,
 3056035,
 3056035,
 3086286,
 3096343,
 3107172,
 3121687,
 3133122,
 3133122,
 3133122,
 3153971,
 3161432,
 3170644,
 3180212,
 3188553,
 3188553,
 3188553,
 3204531,
 3130184,
 3136321,
 3142358,
 3149012,
 3149012,
 3149012,
 3160970,
 3164982,
 3172101,
 3178356,
 3183704,
 3183704,
 3183704,
 3195062,
 3200024,
 3206116,
 3212332,
 3212332,
 3212332,
 3212332,
 3228803,
 3234319,
 3234319,
 3247738,
 3255324,
 3255324,
 3255324,
 3270825,
 3275819,
 3284353,
 3291394,
 3291394,
 3300965,
 3300965,
 3311325,
 3317948,
 3326736,
 3336637,
 3347512,
 3347512,
 3347512,
 3370256,
 3376548,
 3387022,
 3396685,
 3407283,
 3407283,
 3407283,
 3428354,
 3428354,
 3446072,
 3456886,
 3468617,
 3468617,
 3468617,
 3488469,
 3496134,
 3504799,
 3514942,
 3524077,
 3524077,
 3524077,
 3540430,
 3544945,
 3551262,
 3559222,
 3567408,
 3567408,
 3567408,
 3581392,
 3586333,
 3592751,
 3598452,
 3604799,
 3604799,
 3604799,
 3615860,
 3619848,
 3625928,
 3631661,
 3636453,
 3636453,
 3636453,
 3647520,
 3652879,
 3657886,
 3663176]

In [41]:
france_cases

[0,
 0,
 2,
 3,
 3,
 3,
 4,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 14,
 18,
 38,
 57,
 100,
 130,
 191,
 212,
 288,
 426,
 616,
 948,
 1125,
 1411,
 1783,
 2293,
 2293,
 3681,
 4496,
 4532,
 6683,
 7715,
 9124,
 10970,
 12758,
 14463,
 16758,
 20123,
 22372,
 25334,
 29252,
 33047,
 37692,
 40295,
 44649,
 52278,
 57122,
 59228,
 64452,
 47378,
 48233,
 50887,
 47396,
 51251,
 55035,
 56600,
 58045,
 108791,
 111932,
 129380,
 132588,
 145166,
 147057,
 150863,
 151955,
 154402,
 157068,
 158868,
 157158,
 159969,
 161647,
 162280,
 165966,
 169098,
 167643,
 168861,
 169387,
 170179,
 170540,
 171102,
 172219,
 176355,
 177096,
 177627,
 178156,
 178405,
 178719,
 179472,
 179993,
 180635,
 181148,
 181563,
 181703,
 182147,
 182648,
 183130,
 183397,
 184153,
 184699,
 184260,
 184585,
 184840,
 185012,
 188355,
 188949,
 190744,
 190975,
 191382,
 190735,
 187509,
 191869,
 192450,
 193022,
 193363,
 193637,
 194190,
 194815,
 195179,
 195981,
 196478,
 196868,
 197004,
 197667,
 198155,
 198741,
 199528,
 200147,
 200490,
 200632,
 201330,
 201598,
 201853,
 203116,
 203564,
 203158,
 203803,
 204244,
 205234,
 205773,
 206312,
 206670,
 206681,
 207699,
 208153,
 208975,
 209419,
 210134,
 210385,
 210401,
 211824,
 211886,
 212613,
 213182,
 214011,
 214174,
 214178,
 216089,
 216684,
 217605,
 218841,
 219932,
 220020,
 220020,
 222508,
 223072,
 224542,
 225931,
 227239,
 227302,
 227305,
 230665,
 231636,
 233344,
 234945,
 237332,
 237402,
 237437,
 242168,
 243582,
 246180,
 248858,
 251781,
 254991,
 257994,
 258644,
 260763,
 264535,
 269335,
 274344,
 277818,
 282498,
 284474,
 288090,
 288377,
 299580,
 307221,
 312681,
 318047,
 321160,
 326264,
 333377,
 340499,
 349333,
 357927,
 364943,
 369209,
 375947,
 384566,
 394328,
 403837,
 415174,
 421519,
 427915,
 435741,
 445932,
 456171,
 469404,
 482964,
 493500,
 499039,
 509123,
 522414,
 538264,
 554368,
 568588,
 579223,
 583522,
 591527,
 605893,
 618944,
 631380,
 647868,
 660372,
 666011,
 677321,
 696274,
 713676,
 734764,
 761441,
 777378,
 786590,
 800216,
 823218,
 852975,
 878607,
 910711,
 940548,
 954837,
 975213,
 1002635,
 1043448,
 1086285,
 1131550,
 1138166,
 1211176,
 1245658,
 1283208,
 1329820,
 1379294,
 1414364,
 1460543,
 1566634,
 1639235,
 1593159,
 1650965,
 1711917,
 1798572,
 1837134,
 1858558,
 1881171,
 1917577,
 1950205,
 1974270,
 2006227,
 2033419,
 2043469,
 2089071,
 2117968,
 2138704,
 2161968,
 2179638,
 2192768,
 2197830,
 2207751,
 2224505,
 2237506,
 2250280,
 2262757,
 2272520,
 2276874,
 2285238,
 2299466,
 2312253,
 2323764,
 2336646,
 2347595,
 2351006,
 2365043,
 2379718,
 2393590,
 2407079,
 2421026,
 2432559,
 2435751,
 2447406,
 2465126,
 2483524,
 2499529,
 2516957,
 2529756,
 2535716,
 2547577,
 2562615,
 2584333,
 2604595,
 2607688,
 2616510,
 2619616,
 2631110,
 2657624,
 2677666,
 2697014,
 2700480,
 2712975,
 2717059,
 2737884,
 2763116,
 2784883,
 2804743,
 2824920,
 2840864,
 2844680,
 2864360,
 2888292,
 2909723,
 2931040,
 2952449,
 2969091,
 2972889,
 2996784,
 3023661,
 3046371,
 3069695,
 3093619,
 3112055,
 3116355,
 3138498,
 3165449,
 3189405,
 3212640,
 3236685,
 3255920,
 3260308,
 3283645,
 3310051,
 3310071,
 3355678,
 3376266,
 3395981,
 3400324,
 3419210,
 3444888,
 3465964,
 3486673,
 3507904,
 3524450,
 3528856,
 3548452,
 3573638,
 3596156,
 3620283,
 3642654,
 3664700,
 3669354,
 3689534,
 3721061,
 3746475,
 3771691,
 3795687,
 3815639,
 3820369,
 3843241,
 3870144,
 3895430,
 3918937,
 3942243,
 3964078,
 3969612,
 3992755,
 4022429,
 4050558,
 4075735,
 4105527,
 4131874,
 4138345,
 4168411,
 4206912,
 4241973,
 4277171,
 4312510,
 4343097,
 4358910,
 4373607,
 4438999,
 4484659,
 4526530,
 4569164,
 4606185,
 4615295,
 4646014,
 4705068,
 4755779,
 4802457,
 4802545,
 4883174,
 4893971,
 4902025,
 4902985,
 5000155,
 5000314,
 5001685,
 5119585,
 5128140,
 5167265,
 5210772,
 5248853,
 5285304,
 5321176,
 5350521,
 5357229,
 5401305,
 5436229,
 5469674,
 5502014,
 5534656,
 5559121,
 5565080,
 5595403,
 5626985,
 5653533,
 5677835,
 5703505,
 5713393,
 5717160,
 5741537,
 5767541,
 5789283,
 5808421,
 5829166,
 5838294,
 5841593,
 5861384,
 5882882,
 5902343,
 5909386,
 5925071,
 5939019,
 5942370,
 5959593,
 5978650,
 5629983,
 5642786,
 5655397,
 5665101,
 5667331,
 5670486,
 5683143,
 5697076]

In [42]:
germany_cases

[0,
 0,
 0,
 0,
 0,
 1,
 4,
 4,
 4,
 5,
 8,
 10,
 12,
 12,
 12,
 12,
 13,
 13,
 14,
 14,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 17,
 27,
 46,
 48,
 79,
 130,
 159,
 196,
 262,
 482,
 670,
 799,
 1040,
 1176,
 1457,
 1908,
 2078,
 3675,
 4585,
 5795,
 7272,
 9257,
 12327,
 15320,
 19848,
 22213,
 24873,
 29056,
 32986,
 37323,
 43938,
 50871,
 57695,
 62095,
 66885,
 71808,
 77872,
 84794,
 91159,
 96092,
 100123,
 103374,
 107663,
 113296,
 118181,
 122171,
 124908,
 127854,
 130072,
 131359,
 134753,
 137698,
 141397,
 143342,
 145184,
 147065,
 148291,
 150648,
 153129,
 154999,
 156513,
 157770,
 158758,
 159912,
 161539,
 163009,
 164077,
 164967,
 165664,
 166152,
 167007,
 168162,
 169430,
 170588,
 171324,
 171879,
 172576,
 173171,
 174098,
 174478,
 175233,
 175752,
 176369,
 176551,
 177778,
 178473,
 179021,
 179710,
 179986,
 180328,
 180600,
 181200,
 181524,
 182196,
 182922,
 183189,
 183410,
 183594,
 183879,
 184121,
 184472,
 184924,
 185450,
 185750,
 186109,
 186506,
 186522,
 186691,
 187226,
 187267,
 187518,
 187682,
 188252,
 188604,
 189817,
 190299,
 190670,
 191272,
 191768,
 192480,
 192871,
 193371,
 194036,
 194458,
 194693,
 195042,
 195418,
 195893,
 196370,
 196780,
 197198,
 197523,
 198064,
 198343,
 198699,
 199001,
 199332,
 199709,
 199919,
 200180,
 200456,
 200890,
 201450,
 202045,
 202426,
 202735,
 203325,
 203717,
 204276,
 204881,
 205623,
 206278,
 206667,
 207112,
 207707,
 208546,
 209535,
 210399,
 211005,
 211220,
 212111,
 212828,
 214113,
 215039,
 216196,
 216903,
 217288,
 218508,
 219540,
 220859,
 222281,
 223791,
 224488,
 225007,
 226700,
 228120,
 229706,
 231292,
 233029,
 233861,
 234494,
 236122,
 237583,
 239010,
 240571,
 242126,
 242835,
 243305,
 244802,
 246015,
 247411,
 248840,
 250283,
 251058,
 251728,
 253626,
 254957,
 256433,
 258149,
 259735,
 260817,
 261737,
 263222,
 265014,
 266869,
 269048,
 271247,
 272932,
 273965,
 275560,
 277412,
 279025,
 281346,
 283712,
 285026,
 286339,
 288631,
 290471,
 292913,
 295539,
 298374,
 300027,
 301573,
 304673,
 307127,
 311137,
 315941,
 320495,
 323463,
 326309,
 332850,
 337314,
 344487,
 352107,
 359802,
 364664,
 368671,
 377068,
 385591,
 397922,
 403874,
 417350,
 427808,
 437698,
 450258,
 463419,
 479621,
 498354,
 517736,
 531790,
 544346,
 569598,
 577131,
 608611,
 631172,
 653992,
 668114,
 682624,
 689146,
 715693,
 738094,
 762832,
 785093,
 799733,
 802946,
 817526,
 843757,
 867484,
 891525,
 914118,
 927990,
 932367,
 946822,
 963192,
 995879,
 1017830,
 1038649,
 1052494,
 1055691,
 1069912,
 1094678,
 1117953,
 1141544,
 1157514,
 1183640,
 1194550,
 1200006,
 1229269,
 1254358,
 1287092,
 1314309,
 1336101,
 1350810,
 1357261,
 1391086,
 1423830,
 1454009,
 1486839,
 1508518,
 1514962,
 1534218,
 1570371,
 1604129,
 1630596,
 1632736,
 1646240,
 1658639,
 1672643,
 1692109,
 1741153,
 1760520,
 1762637,
 1773540,
 1783896,
 1796216,
 1814565,
 1841228,
 1886561,
 1905638,
 1928462,
 1929410,
 1941116,
 1968326,
 1993892,
 2015235,
 2023828,
 2038645,
 2050129,
 2059382,
 2071615,
 2100618,
 2108895,
 2125261,
 2137691,
 2147769,
 2154656,
 2164043,
 2179679,
 2194562,
 2207393,
 2224911,
 2225659,
 2232327,
 2240017,
 2252504,
 2265536,
 2276371,
 2285003,
 2291673,
 2296323,
 2302051,
 2311297,
 2321225,
 2330422,
 2336906,
 2341744,
 2346876,
 2352766,
 2362364,
 2372209,
 2381259,
 2388421,
 2394515,
 2399499,
 2405263,
 2416037,
 2427069,
 2436506,
 2444177,
 2450295,
 2455569,
 2462061,
 2472913,
 2484306,
 2493887,
 2502151,
 2508655,
 2513784,
 2520618,
 2541781,
 2546526,
 2559296,
 2569864,
 2578842,
 2585385,
 2603064,
 2610769,
 2639258,
 2654734,
 2669233,
 2670001,
 2678262,
 2699231,
 2722988,
 2744608,
 2765297,
 2782925,
 2784652,
 2794949,
 2818630,
 2843644,
 2866323,
 2882356,
 2886029,
 2896329,
 2902309,
 2909902,
 2940279,
 2966789,
 2990724,
 3009452,
 3012158,
 3024604,
 3054025,
 3085142,
 3110252,
 3134108,
 3154305,
 3155522,
 3167137,
 3198534,
 3222888,
 3254609,
 3276871,
 3291293,
 3306692,
 3312653,
 3338564,
 3366827,
 3391039,
 3405365,
 3423900,
 3432676,
 3438186,
 3462297,
 3484755,
 3502672,
 3517762,
 3530887,
 3530887,
 3538208,
 3557904,
 3564494,
 3578125,
 3588502,
 3595872,
 3602939,
 3608320,
 3615896,
 3627777,
 3638504,
 3646600,
 3653019,
 3657662,
 3659990,
 3662568,
 3667041,
 3673990]

In [43]:
uk_cases

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 8,
 8,
 9,
 9,
 9,
 13,
 14,
 14,
 15,
 16,
 17,
 18,
 18,
 18,
 19,
 19,
 20,
 22,
 23,
 23,
 28,
 30,
 34,
 37,
 44,
 56,
 61,
 94,
 134,
 189,
 246,
 295,
 374,
 429,
 483,
 630,
 889,
 1301,
 1790,
 2270,
 2634,
 3077,
 3692,
 4462,
 5468,
 6534,
 7792,
 9007,
 10395,
 12744,
 15126,
 17843,
 20970,
 24219,
 27062,
 29954,
 34281,
 38815,
 43789,
 48718,
 53699,
 57772,
 61422,
 66738,
 72224,
 77387,
 82293,
 86660,
 90273,
 93812,
 98017,
 102365,
 107465,
 112808,
 117798,
 122534,
 126394,
 131260,
 136035,
 141540,
 146708,
 151689,
 155453,
 158926,
 163630,
 168357,
 173807,
 178771,
 183501,
 186731,
 189708,
 193091,
 196780,
 200616,
 204387,
 207439,
 209589,
 211911,
 215500,
 218895,
 222195,
 224813,
 227334,
 229406,
 231232,
 233809,
 236867,
 239579,
 242133,
 244174,
 245682,
 247037,
 248650,
 250309,
 252118,
 253854,
 255362,
 256469,
 257539,
 258983,
 260453,
 261802,
 263040,
 264150,
 264944,
 265662,
 266756,
 267915,
 269101,
 270108,
 271162,
 272050,
 272857,
 273888,
 274971,
 275970,
 276990,
 277974,
 278640,
 279264,
 280156,
 281038,
 281815,
 282512,
 283151,
 283785,
 284192,
 284812,
 285216,
 285279,
 285285,
 285787,
 286412,
 286931,
 287290,
 287874,
 288511,
 289154,
 289678,
 290504,
 291154,
 291691,
 292931,
 293469,
 294116,
 294803,
 295632,
 296358,
 296944,
 297389,
 297952,
 298731,
 299500,
 300270,
 301020,
 301708,
 302261,
 303063,
 303910,
 304793,
 305562,
 306309,
 307251,
 307926,
 308832,
 309796,
 310696,
 311461,
 312574,
 313392,
 314542,
 315581,
 316729,
 318190,
 319232,
 320343,
 321064,
 322177,
 323008,
 324203,
 325263,
 326595,
 327643,
 328620,
 329821,
 330967,
 332509,
 333806,
 334916,
 336668,
 338083,
 339415,
 340929,
 342708,
 344686,
 346513,
 349500,
 352453,
 354934,
 357615,
 360546,
 364090,
 367594,
 370932,
 373557,
 376672,
 380679,
 384089,
 388418,
 392847,
 396746,
 401124,
 406060,
 412247,
 418891,
 425769,
 431819,
 437519,
 441575,
 448731,
 455848,
 462777,
 469771,
 482656,
 505621,
 518224,
 532781,
 546954,
 564504,
 578392,
 593567,
 606449,
 620460,
 637710,
 657461,
 676457,
 692114,
 708300,
 725294,
 744124,
 765489,
 792196,
 813453,
 834012,
 857045,
 876842,
 897742,
 920666,
 945380,
 968458,
 992876,
 1014795,
 1038056,
 1057023,
 1077101,
 1102307,
 1126471,
 1149793,
 1174772,
 1195352,
 1216749,
 1237200,
 1260200,
 1293717,
 1321033,
 1347909,
 1372886,
 1394302,
 1414362,
 1434007,
 1456943,
 1477217,
 1497138,
 1515805,
 1531270,
 1542614,
 1560875,
 1578432,
 1593253,
 1609144,
 1621308,
 1633736,
 1647233,
 1663470,
 1678421,
 1694803,
 1710382,
 1727754,
 1742528,
 1754914,
 1771548,
 1792614,
 1814398,
 1835952,
 1854493,
 1874870,
 1893439,
 1918739,
 1954271,
 1982831,
 2010080,
 2046164,
 2079681,
 2116612,
 2155999,
 2195148,
 2227951,
 2262739,
 2295232,
 2336692,
 2389967,
 2440206,
 2496235,
 2549693,
 2607546,
 2662703,
 2721626,
 2782713,
 2845269,
 2898056,
 2966248,
 3026346,
 3081372,
 3127647,
 3173295,
 3220957,
 3269761,
 3325646,
 3367074,
 3405744,
 3443354,
 3476808,
 3515800,
 3553777,
 3594098,
 3627750,
 3657861,
 3680105,
 3700272,
 3725641,
 3754452,
 3783597,
 3806997,
 3828187,
 3846855,
 3863761,
 3882976,
 3903710,
 3922914,
 3941277,
 3957181,
 3971319,
 3983760,
 3996837,
 4010380,
 4025578,
 4038933,
 4049924,
 4059700,
 4070336,
 4083096,
 4095191,
 4107290,
 4117743,
 4127578,
 4138237,
 4146760,
 4156707,
 4166727,
 4175315,
 4182772,
 4188827,
 4194289,
 4200700,
 4207120,
 4213764,
 4219788,
 4225906,
 4231166,
 4235989,
 4241858,
 4247879,
 4254714,
 4261398,
 4267015,
 4271710,
 4276840,
 4282203,
 4287996,
 4294328,
 4299200,
 4304839,
 4310195,
 4315602,
 4321019,
 4326645,
 4332922,
 4339157,
 4343066,
 4347013,
 4351796,
 4355867,
 4359982,
 4364547,
 4367969,
 4371393,
 4373798,
 4376629,
 4379033,
 4381830,
 4384954,
 4380167,
 4382880,
 4384610,
 4388296,
 4390801,
 4393330,
 4396096,
 4398903,
 4401176,
 4403060,
 4406114,
 4408644,
 4411068,
 4413834,
 4416588,
 4418710,
 4420443,
 4422562,
 4425259,
 4427390,
 4429849,
 4432246,
 4434157,
 4435831,
 4437505,
 4439489,
 4441644,
 4444262,
 4446752,
 4448808,
 4450578,
 4452956,
 4455446,
 4457742,
 4460405,
 4462603,
 4464663,
 4466589,
 4468582,
 4466220,
 4468366,
 4471065,
 4473773,
 4476297,
 4478390,
 4480760,
 4483177,
 4486168,
 4489552]

In [44]:
russia_cases

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 4,
 13,
 13,
 17,
 17,
 20,
 20,
 28,
 45,
 59,
 63,
 90,
 114,
 147,
 199,
 253,
 306,
 367,
 438,
 495,
 658,
 840,
 1036,
 1264,
 1534,
 1836,
 2337,
 2777,
 3548,
 4149,
 4731,
 5389,
 6343,
 7497,
 8672,
 10131,
 11917,
 13584,
 15770,
 18328,
 21102,
 24490,
 27938,
 32008,
 36793,
 42853,
 47121,
 52763,
 57999,
 62773,
 68622,
 74588,
 80949,
 87147,
 93558,
 99399,
 106498,
 114431,
 124054,
 134687,
 145268,
 155370,
 165929,
 177160,
 187859,
 198676,
 209688,
 221344,
 232243,
 242271,
 252245,
 262843,
 272043,
 281752,
 290678,
 299941,
 308705,
 317554,
 326448,
 335882,
 344481,
 353427,
 362342,
 370680,
 379051,
 387623,
 396575,
 405843,
 414328,
 423186,
 431715,
 440538,
 449256,
 458102,
 467073,
 476043,
 484630,
 493023,
 501800,
 510761,
 519458,
 528267,
 536484,
 544725,
 552549,
 560321,
 568292,
 576162,
 583879,
 591465,
 598878,
 606043,
 613148,
 619936,
 626779,
 633563,
 640246,
 646929,
 653479,
 660231,
 666941,
 673564,
 680283,
 686852,
 693215,
 699749,
 706240,
 712863,
 719449,
 726036,
 732547,
 738787,
 745197,
 751612,
 758001,
 764215,
 770311,
 776212,
 782040,
 787890,
 793720,
 799499,
 805332,
 811073,
 816680,
 822060,
 827509,
 832993,
 838461,
 843890,
 849277,
 854641,
 859762,
 864948,
 870187,
 875378,
 880563,
 885718,
 890799,
 895691,
 900745,
 905762,
 910778,
 915808,
 920719,
 925558,
 930276,
 935066,
 939833,
 944671,
 949531,
 954328,
 959016,
 963655,
 968297,
 972972,
 977730,
 982573,
 987470,
 992402,
 997072,
 1001965,
 1006923,
 1011987,
 1017131,
 1022228,
 1027334,
 1032354,
 1037526,
 1042836,
 1048257,
 1053663,
 1059024,
 1064438,
 1069873,
 1075485,
 1081152,
 1086955,
 1092915,
 1098958,
 1105048,
 1111157,
 1117487,
 1123976,
 1131088,
 1138509,
 1146273,
 1154299,
 1162428,
 1170799,
 1179634,
 1188928,
 1198663,
 1209039,
 1219796,
 1231277,
 1242258,
 1253603,
 1265572,
 1278245,
 1291687,
 1305093,
 1318783,
 1332824,
 1346380,
 1361317,
 1376020,
 1390824,
 1406667,
 1422775,
 1438219,
 1453923,
 1471000,
 1487260,
 1503652,
 1520800,
 1537142,
 1553028,
 1570446,
 1588433,
 1606267,
 1624648,
 1642665,
 1661096,
 1680579,
 1699695,
 1720063,
 1740172,
 1760420,
 1781997,
 1802762,
 1822345,
 1843678,
 1865395,
 1887836,
 1910149,
 1932711,
 1954912,
 1975629,
 1998966,
 2023025,
 2047563,
 2071858,
 2096749,
 2120836,
 2144229,
 2169424,
 2196691,
 2223500,
 2249890,
 2275936,
 2302062,
 2327105,
 2354934,
 2382012,
 2410462,
 2439163,
 2466961,
 2492713,
 2518551,
 2546113,
 2574319,
 2602048,
 2629699,
 2656601,
 2682866,
 2708940,
 2736727,
 2764843,
 2792615,
 2821125,
 2850042,
 2878382,
 2905196,
 2934695,
 2963290,
 2992123,
 3019972,
 3047335,
 3073923,
 3100018,
 3127347,
 3153960,
 3179898,
 3203743,
 3226758,
 3250713,
 3274615,
 3297833,
 3321163,
 3344175,
 3366715,
 3389733,
 3412390,
 3434934,
 3459237,
 3483531,
 3507201,
 3530379,
 3552888,
 3574330,
 3595136,
 3616680,
 3637862,
 3658447,
 3679247,
 3698246,
 3716228,
 3733692,
 3752548,
 3771514,
 3790265,
 3808348,
 3825739,
 3842145,
 3858367,
 3874830,
 3891274,
 3907653,
 3923461,
 3939162,
 3953970,
 3968228,
 3983031,
 3997898,
 4012538,
 4026506,
 4040505,
 4053535,
 4066164,
 4079407,
 4092649,
 4105424,
 4117992,
 4130447,
 4142126,
 4153735,
 4164802,
 4175757,
 4187166,
 4198400,
 4209850,
 4220291,
 4230707,
 4241970,
 4252876,
 4263785,
 4274263,
 4284408,
 4293750,
 4302726,
 4311893,
 4321588,
 4331396,
 4341381,
 4350728,
 4360033,
 4368943,
 4378656,
 4388268,
 4397816,
 4407031,
 4416226,
 4424595,
 4433364,
 4442492,
 4451565,
 4460348,
 4469327,
 4477916,
 4486078,
 4494234,
 4503291,
 4511973,
 4520879,
 4529576,
 4538101,
 4546307,
 4554481,
 4563026,
 4572053,
 4580633,
 4589209,
 4597400,
 4605444,
 4613646,
 4622464,
 4631336,
 4640537,
 4649044,
 4657509,
 4665553,
 4673699,
 4682573,
 4691290,
 4699988,
 4708640,
 4717321,
 4725252,
 4732981,
 4742142,
 4750755,
 4759902,
 4768476,
 4776844,
 4784497,
 4792354,
 4799872,
 4808133,
 4816331,
 4824621,
 4832959,
 4840948,
 4849044,
 4857303,
 4866641,
 4875308,
 4883734,
 4892938,
 4900995,
 4908794,
 4917906,
 4926717,
 4935302,
 4944129,
 4952412,
 4960174,
 4968421,
 4977332]

In [45]:
india_cases

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 5,
 28,
 30,
 31,
 34,
 39,
 43,
 56,
 62,
 73,
 82,
 102,
 113,
 119,
 142,
 156,
 194,
 244,
 330,
 396,
 499,
 536,
 657,
 727,
 887,
 987,
 1024,
 1251,
 1397,
 1998,
 2543,
 2567,
 3082,
 3588,
 4778,
 5311,
 5916,
 6725,
 7598,
 8446,
 9205,
 10453,
 11487,
 12322,
 13430,
 14352,
 15722,
 17615,
 18539,
 20080,
 21370,
 23077,
 24530,
 26283,
 27890,
 29451,
 31324,
 33062,
 34863,
 37257,
 39699,
 42505,
 46437,
 49400,
 52987,
 56351,
 59695,
 62808,
 67161,
 70768,
 74292,
 78055,
 81997,
 85784,
 90648,
 95698,
 100328,
 106475,
 112028,
 118226,
 124794,
 131423,
 138536,
 144950,
 150793,
 158086,
 165386,
 173491,
 181827,
 190609,
 198370,
 207191,
 216824,
 226713,
 236184,
 246622,
 257486,
 265928,
 276146,
 286605,
 297535,
 308993,
 320922,
 332424,
 343091,
 354065,
 366946,
 380532,
 395048,
 410451,
 425282,
 440215,
 456183,
 473105,
 490401,
 508953,
 528859,
 548318,
 566840,
 585481,
 604641,
 625544,
 648315,
 673165,
 697413,
 719664,
 742417,
 767296,
 793802,
 820916,
 849522,
 878254,
 906752,
 936181,
 968857,
 1003832,
 1039084,
 1077781,
 1118206,
 1155338,
 1193078,
 1238798,
 1288108,
 1337024,
 1385635,
 1435616,
 1480073,
 1531669,
 1581963,
 1634746,
 1695988,
 1750723,
 1803695,
 1855745,
 1908254,
 1964536,
 2027074,
 2088611,
 2153010,
 2215074,
 2268675,
 2329638,
 2396637,
 2461190,
 2525922,
 2589952,
 2647663,
 2702681,
 2767253,
 2836925,
 2905825,
 2975701,
 3044940,
 3106348,
 3167323,
 3224547,
 3310234,
 3387500,
 3463972,
 3542733,
 3621245,
 3691166,
 3769523,
 3853406,
 3936747,
 4023179,
 4113811,
 4204613,
 4280422,
 4370128,
 4465863,
 4562414,
 4659984,
 4754356,
 4846427,
 4930236,
 5020359,
 5118253,
 5214677,
 5308014,
 5400619,
 5487580,
 5562663,
 5646010,
 5732518,
 5818570,
 5903932,
 5992532,
 6074702,
 6145291,
 6225763,
 6312584,
 6394068,
 6473544,
 6549373,
 6623815,
 6685082,
 6757131,
 6835655,
 6906151,
 6979423,
 7053806,
 7120538,
 7175880,
 7239389,
 7307097,
 7370468,
 7432680,
 7494551,
 7550273,
 7597063,
 7651107,
 7706946,
 7761312,
 7814682,
 7864811,
 7909959,
 7946429,
 7990322,
 8040203,
 8088851,
 8137119,
 8184082,
 8229313,
 8267623,
 8313876,
 8364086,
 8411724,
 8462080,
 8507754,
 8553657,
 8591730,
 8636011,
 8683916,
 8728795,
 8773479,
 8814579,
 8845127,
 8874290,
 8912907,
 8958483,
 9004365,
 9050597,
 9095806,
 9139865,
 9177840,
 9222216,
 9266705,
 9309787,
 9351109,
 9392919,
 9431691,
 9462809,
 9499413,
 9534964,
 9571559,
 9608211,
 9644222,
 9677203,
 9703770,
 9735850,
 9767371,
 9796744,
 9826775,
 9857029,
 9884100,
 9906165,
 9932547,
 9956557,
 9979447,
 10004599,
 10031223,
 10055560,
 10075116,
 10099066,
 10123778,
 10146845,
 10169118,
 10187850,
 10207871,
 10224303,
 10244852,
 10266674,
 10266674,
 10286709,
 10323965,
 10340469,
 10356844,
 10374932,
 10395278,
 10413417,
 10413417,
 10450284,
 10466595,
 10479179,
 10495147,
 10512093,
 10527683,
 10542841,
 10557985,
 10571773,
 10581823,
 10595639,
 10610883,
 10625428,
 10639684,
 10654533,
 10667736,
 10676838,
 10689527,
 10701193,
 10720048,
 10733130,
 10746174,
 10757610,
 10766245,
 10777284,
 10790183,
 10802591,
 10814304,
 10826363,
 10838194,
 10847304,
 10858371,
 10871294,
 10880603,
 10892746,
 10904940,
 10916589,
 10925710,
 10937320,
 10950201,
 10963394,
 10977387,
 10991651,
 11005850,
 11016434,
 11030176,
 11046914,
 11063491,
 11079979,
 11096731,
 11112241,
 11124527,
 11139516,
 11156923,
 11173761,
 11192045,
 11210799,
 11229398,
 11244786,
 11262707,
 11285561,
 11308846,
 11333728,
 11359048,
 11385339,
 11409831,
 11438734,
 11474605,
 11514331,
 11555284,
 11599130,
 11646081,
 11686796,
 11734058,
 11787534,
 11846652,
 11908910,
 11971624,
 12039644,
 12095855,
 12149335,
 12221665,
 12303131,
 12392260,
 12485509,
 12589067,
 12686049,
 12801785,
 12928574,
 13060542,
 13205926,
 13358805,
 13527717,
 13689453,
 13873825,
 14074564,
 14291917,
 14526609,
 14788003,
 15061805,
 15320972,
 15616130,
 15930774,
 16263695,
 16610481,
 16960172,
 17313163,
 17636186,
 17997113,
 18376421,
 18762976,
 19164969,
 19557457,
 19925517,
 20282833,
 20664979,
 21077410,
 21491598,
 21892676,
 22296081,
 22662575,
 22992517,
 23340938,
 23703665,
 24046809,
 24372907,
 24684077,
 24965463,
 25228996,
 25496330,
 25772440,
 26031991,
 26289290,
 26530132,
 26752447,
 26948874,
 27157795,
 27369093,
 27555457]

In [46]:
def daily_increase(data):
    d = [] 
    for i in range(len(data)):
        #print(i)
        if i == 0:
            d.append(data[0])
            #print(d)
        else:
            d.append(data[i]-data[i-1])
            
    return d

In [47]:
#confirmed cases:
world_daily_increase = daily_increase(world_cases)
china_daily_increase = daily_increase(china_cases)
italy_daily_increase = daily_increase(italy_cases)
us_daily_increase = daily_increase(us_cases)
spain_daily_increase = daily_increase(spain_cases)
france_daily_increase = daily_increase(france_cases)
germany_daily_increase = daily_increase(germany_cases)
uk_daily_increase = daily_increase(uk_cases)
india_daily_increase = daily_increase(india_cases)

In [48]:
world_daily_increase

[557,
 98,
 286,
 492,
 685,
 809,
 2651,
 589,
 2068,
 1692,
 2111,
 4749,
 3100,
 4011,
 3745,
 3160,
 3593,
 2734,
 3030,
 2609,
 2042,
 418,
 15153,
 6527,
 2143,
 2183,
 2035,
 1882,
 500,
 560,
 629,
 1761,
 380,
 564,
 853,
 977,
 1360,
 1386,
 1891,
 2381,
 1983,
 2594,
 2308,
 2811,
 3913,
 4095,
 3949,
 4172,
 4822,
 7661,
 5790,
 14384,
 11074,
 11269,
 14808,
 15943,
 19565,
 27049,
 30775,
 31991,
 34855,
 42835,
 41179,
 51001,
 62877,
 65041,
 67280,
 59237,
 65294,
 76845,
 82808,
 83060,
 83559,
 58363,
 72592,
 73155,
 69831,
 83378,
 87014,
 85534,
 74283,
 119696,
 70742,
 84011,
 77114,
 95531,
 87997,
 77240,
 76605,
 76018,
 75749,
 81247,
 84249,
 84096,
 82259,
 71588,
 70192,
 75540,
 77110,
 83495,
 88376,
 79200,
 76373,
 77689,
 80502,
 90028,
 88706,
 90279,
 85223,
 74976,
 76631,
 84491,
 84980,
 96231,
 95732,
 94439,
 78022,
 89167,
 96775,
 101878,
 106644,
 106422,
 104804,
 94211,
 86717,
 93967,
 102762,
 119283,
 120903,
 136515,
 106408,
 95995,
 121964,
 114249,
 130944,
 131223,
 133737,
 112363,
 102497,
 125060,
 135105,
 138020,
 128765,
 135289,
 132284,
 119658,
 142084,
 143746,
 141063,
 179915,
 157448,
 127702,
 139361,
 166809,
 172594,
 178381,
 191597,
 178132,
 163871,
 155347,
 174542,
 217607,
 209945,
 201385,
 193809,
 184003,
 163975,
 211362,
 214159,
 226827,
 232674,
 216482,
 192274,
 191444,
 222188,
 231468,
 251312,
 242742,
 236178,
 213434,
 207116,
 233681,
 279868,
 282854,
 281074,
 254054,
 213036,
 226530,
 252785,
 291728,
 280100,
 290744,
 248338,
 230992,
 206475,
 257942,
 276575,
 285202,
 282239,
 258518,
 224683,
 226029,
 257570,
 276647,
 289216,
 303748,
 247708,
 214470,
 207732,
 258256,
 279590,
 272554,
 261205,
 264251,
 206149,
 225268,
 244001,
 283793,
 283895,
 283627,
 263793,
 220965,
 262891,
 264925,
 283504,
 281419,
 314016,
 269991,
 230465,
 217882,
 242199,
 284822,
 299876,
 321370,
 286578,
 242719,
 263752,
 285462,
 304535,
 314886,
 325921,
 292119,
 252114,
 276086,
 284514,
 276092,
 353037,
 330870,
 288442,
 251391,
 254780,
 282668,
 326210,
 318303,
 297866,
 332044,
 261397,
 301023,
 326519,
 350997,
 361327,
 360897,
 357101,
 286912,
 291766,
 319259,
 382334,
 406984,
 411771,
 372657,
 316563,
 387210,
 389002,
 444890,
 472719,
 496798,
 456784,
 360653,
 486411,
 470233,
 511872,
 550415,
 571055,
 476765,
 462384,
 563127,
 553745,
 511552,
 596558,
 644854,
 596892,
 483974,
 501532,
 559377,
 648606,
 649543,
 652073,
 594970,
 473941,
 534457,
 611220,
 627103,
 653585,
 668744,
 587564,
 487981,
 525319,
 590261,
 636224,
 582475,
 687148,
 586031,
 488583,
 508641,
 612097,
 651398,
 694328,
 683276,
 642163,
 538754,
 520019,
 643528,
 669911,
 1498213,
 704497,
 634850,
 530838,
 525387,
 636206,
 733726,
 739582,
 720462,
 611253,
 533473,
 549297,
 650261,
 695122,
 666640,
 465550,
 512602,
 438453,
 496323,
 664428,
 761230,
 725009,
 533018,
 626359,
 532796,
 554118,
 740122,
 783372,
 880837,
 803222,
 760994,
 589134,
 619930,
 705508,
 748388,
 755228,
 767187,
 639144,
 529212,
 515066,
 608426,
 692937,
 656323,
 659061,
 568124,
 445654,
 497340,
 556238,
 598361,
 614251,
 590443,
 515330,
 381639,
 446774,
 457957,
 521981,
 466907,
 535428,
 372125,
 398078,
 315893,
 428033,
 435741,
 441465,
 428689,
 373301,
 293850,
 283166,
 351020,
 395555,
 403516,
 412519,
 370455,
 314446,
 288438,
 388853,
 444936,
 447478,
 443039,
 389230,
 303509,
 305864,
 310288,
 441142,
 453049,
 447054,
 410533,
 368312,
 298723,
 414665,
 467079,
 476896,
 489328,
 454116,
 360385,
 348901,
 473013,
 539285,
 553723,
 561679,
 498820,
 423315,
 416821,
 514245,
 633581,
 651350,
 641351,
 584592,
 469958,
 458405,
 568273,
 683205,
 711787,
 633739,
 529443,
 552803,
 489584,
 604087,
 684346,
 839850,
 748045,
 664507,
 690741,
 616625,
 779567,
 817025,
 816761,
 854855,
 788042,
 685495,
 693422,
 854425,
 889975,
 899755,
 903747,
 820940,
 722356,
 682784,
 844470,
 905992,
 897602,
 879014,
 796679,
 674348,
 681590,
 807436,
 841224,
 869972,
 831558,
 786546,
 641539,
 621929,
 738473,
 760099,
 725275,
 718060,
 627518,
 548206,
 539694,
 622185,
 671092,
 279413,
 625876,
 577795,
 476075,
 454300,
 531845,
 560509,
 557653]

In [49]:
india_daily_increase

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 23,
 2,
 1,
 3,
 5,
 4,
 13,
 6,
 11,
 9,
 20,
 11,
 6,
 23,
 14,
 38,
 50,
 86,
 66,
 103,
 37,
 121,
 70,
 160,
 100,
 37,
 227,
 146,
 601,
 545,
 24,
 515,
 506,
 1190,
 533,
 605,
 809,
 873,
 848,
 759,
 1248,
 1034,
 835,
 1108,
 922,
 1370,
 1893,
 924,
 1541,
 1290,
 1707,
 1453,
 1753,
 1607,
 1561,
 1873,
 1738,
 1801,
 2394,
 2442,
 2806,
 3932,
 2963,
 3587,
 3364,
 3344,
 3113,
 4353,
 3607,
 3524,
 3763,
 3942,
 3787,
 4864,
 5050,
 4630,
 6147,
 5553,
 6198,
 6568,
 6629,
 7113,
 6414,
 5843,
 7293,
 7300,
 8105,
 8336,
 8782,
 7761,
 8821,
 9633,
 9889,
 9471,
 10438,
 10864,
 8442,
 10218,
 10459,
 10930,
 11458,
 11929,
 11502,
 10667,
 10974,
 12881,
 13586,
 14516,
 15403,
 14831,
 14933,
 15968,
 16922,
 17296,
 18552,
 19906,
 19459,
 18522,
 18641,
 19160,
 20903,
 22771,
 24850,
 24248,
 22251,
 22753,
 24879,
 26506,
 27114,
 28606,
 28732,
 28498,
 29429,
 32676,
 34975,
 35252,
 38697,
 40425,
 37132,
 37740,
 45720,
 49310,
 48916,
 48611,
 49981,
 44457,
 51596,
 50294,
 52783,
 61242,
 54735,
 52972,
 52050,
 52509,
 56282,
 62538,
 61537,
 64399,
 62064,
 53601,
 60963,
 66999,
 64553,
 64732,
 64030,
 57711,
 55018,
 64572,
 69672,
 68900,
 69876,
 69239,
 61408,
 60975,
 57224,
 85687,
 77266,
 76472,
 78761,
 78512,
 69921,
 78357,
 83883,
 83341,
 86432,
 90632,
 90802,
 75809,
 89706,
 95735,
 96551,
 97570,
 94372,
 92071,
 83809,
 90123,
 97894,
 96424,
 93337,
 92605,
 86961,
 75083,
 83347,
 86508,
 86052,
 85362,
 88600,
 82170,
 70589,
 80472,
 86821,
 81484,
 79476,
 75829,
 74442,
 61267,
 72049,
 78524,
 70496,
 73272,
 74383,
 66732,
 55342,
 63509,
 67708,
 63371,
 62212,
 61871,
 55722,
 46790,
 54044,
 55839,
 54366,
 53370,
 50129,
 45148,
 36470,
 43893,
 49881,
 48648,
 48268,
 46963,
 45231,
 38310,
 46253,
 50210,
 47638,
 50356,
 45674,
 45903,
 38073,
 44281,
 47905,
 44879,
 44684,
 41100,
 30548,
 29163,
 38617,
 45576,
 45882,
 46232,
 45209,
 44059,
 37975,
 44376,
 44489,
 43082,
 41322,
 41810,
 38772,
 31118,
 36604,
 35551,
 36595,
 36652,
 36011,
 32981,
 26567,
 32080,
 31521,
 29373,
 30031,
 30254,
 27071,
 22065,
 26382,
 24010,
 22890,
 25152,
 26624,
 24337,
 19556,
 23950,
 24712,
 23067,
 22273,
 18732,
 20021,
 16432,
 20549,
 21822,
 0,
 20035,
 37256,
 16504,
 16375,
 18088,
 20346,
 18139,
 0,
 36867,
 16311,
 12584,
 15968,
 16946,
 15590,
 15158,
 15144,
 13788,
 10050,
 13816,
 15244,
 14545,
 14256,
 14849,
 13203,
 9102,
 12689,
 11666,
 18855,
 13082,
 13044,
 11436,
 8635,
 11039,
 12899,
 12408,
 11713,
 12059,
 11831,
 9110,
 11067,
 12923,
 9309,
 12143,
 12194,
 11649,
 9121,
 11610,
 12881,
 13193,
 13993,
 14264,
 14199,
 10584,
 13742,
 16738,
 16577,
 16488,
 16752,
 15510,
 12286,
 14989,
 17407,
 16838,
 18284,
 18754,
 18599,
 15388,
 17921,
 22854,
 23285,
 24882,
 25320,
 26291,
 24492,
 28903,
 35871,
 39726,
 40953,
 43846,
 46951,
 40715,
 47262,
 53476,
 59118,
 62258,
 62714,
 68020,
 56211,
 53480,
 72330,
 81466,
 89129,
 93249,
 103558,
 96982,
 115736,
 126789,
 131968,
 145384,
 152879,
 168912,
 161736,
 184372,
 200739,
 217353,
 234692,
 261394,
 273802,
 259167,
 295158,
 314644,
 332921,
 346786,
 349691,
 352991,
 323023,
 360927,
 379308,
 386555,
 401993,
 392488,
 368060,
 357316,
 382146,
 412431,
 414188,
 401078,
 403405,
 366494,
 329942,
 348421,
 362727,
 343144,
 326098,
 311170,
 281386,
 263533,
 267334,
 276110,
 259551,
 257299,
 240842,
 222315,
 196427,
 208921,
 211298,
 186364]

In [50]:
# deaths
world_daily_death = daily_increase(total_deaths)
china_daily_death = daily_increase(china_deaths)
italy_daily_death = daily_increase(italy_deaths)
us_daily_death = daily_increase(us_deaths)
spain_daily_death = daily_increase(spain_deaths)
france_daily_death = daily_increase(france_deaths)
germany_daily_death = daily_increase(germany_deaths)
uk_daily_death = daily_increase(uk_deaths)
india_daily_death = daily_increase(india_deaths)

In [51]:
world_daily_death

[17,
 1,
 8,
 16,
 14,
 26,
 49,
 2,
 38,
 42,
 46,
 103,
 64,
 66,
 72,
 70,
 85,
 87,
 100,
 107,
 100,
 5,
 253,
 152,
 143,
 104,
 98,
 140,
 115,
 125,
 4,
 207,
 11,
 160,
 80,
 61,
 43,
 59,
 69,
 54,
 89,
 75,
 95,
 94,
 111,
 104,
 239,
 190,
 274,
 344,
 306,
 497,
 420,
 641,
 678,
 814,
 907,
 1111,
 1485,
 1722,
 1686,
 1949,
 2290,
 2810,
 3035,
 3488,
 3730,
 3519,
 4081,
 4748,
 5998,
 5887,
 6161,
 5914,
 5188,
 5938,
 8258,
 6811,
 7784,
 7378,
 6172,
 5859,
 5966,
 6970,
 8473,
 7259,
 8394,
 6145,
 5233,
 5872,
 7273,
 6864,
 6828,
 6770,
 5628,
 3979,
 4746,
 6578,
 6725,
 5842,
 5151,
 5495,
 3511,
 4213,
 5823,
 6505,
 5310,
 5552,
 4225,
 3559,
 3486,
 5485,
 5132,
 5169,
 5221,
 4176,
 3187,
 3763,
 4647,
 4779,
 4659,
 5244,
 3927,
 3016,
 1212,
 4242,
 5056,
 4552,
 4608,
 4024,
 2692,
 3073,
 4677,
 5432,
 5034,
 4578,
 3769,
 2740,
 3702,
 4774,
 5043,
 4640,
 4209,
 4116,
 3400,
 3416,
 6710,
 5147,
 4910,
 6066,
 4109,
 4014,
 3562,
 5217,
 5175,
 4692,
 4748,
 4463,
 3166,
 3678,
 4885,
 4945,
 5075,
 4927,
 4404,
 3489,
 3845,
 5967,
 5275,
 5407,
 5299,
 4818,
 3987,
 3911,
 5597,
 5446,
 5772,
 6668,
 5597,
 4084,
 4211,
 6169,
 6946,
 9888,
 6030,
 5569,
 3713,
 5183,
 6265,
 6607,
 6050,
 6186,
 5455,
 4326,
 4686,
 6530,
 7051,
 6491,
 6288,
 5414,
 4573,
 5352,
 6199,
 6568,
 6214,
 10139,
 5356,
 4264,
 4181,
 6807,
 6727,
 6072,
 5438,
 5498,
 3954,
 4506,
 6286,
 6226,
 5896,
 5529,
 5322,
 4045,
 4177,
 6399,
 6109,
 5684,
 5869,
 4940,
 3846,
 9374,
 4913,
 6105,
 5804,
 5851,
 4881,
 3715,
 4440,
 6426,
 5780,
 5468,
 5668,
 5279,
 3739,
 4102,
 5972,
 5610,
 6654,
 5903,
 5345,
 3687,
 3975,
 5903,
 6464,
 8715,
 4936,
 5364,
 3839,
 6946,
 5776,
 5836,
 6278,
 6150,
 4882,
 4033,
 3983,
 5286,
 6073,
 6115,
 6185,
 5597,
 3542,
 4836,
 6554,
 6630,
 5935,
 6971,
 5817,
 4211,
 5517,
 7372,
 7160,
 7086,
 7599,
 6578,
 5010,
 6104,
 9345,
 10251,
 8014,
 9661,
 7600,
 5875,
 7223,
 9993,
 10451,
 9766,
 9588,
 9082,
 6425,
 7954,
 11071,
 11414,
 11033,
 11887,
 8972,
 7195,
 8526,
 12660,
 12131,
 10888,
 11387,
 9283,
 7160,
 8880,
 12686,
 12589,
 12575,
 12520,
 10289,
 7428,
 8715,
 12280,
 12720,
 12696,
 13028,
 10545,
 7459,
 9172,
 13953,
 13659,
 13451,
 12790,
 10772,
 7915,
 9647,
 14313,
 13803,
 11631,
 8602,
 7399,
 7399,
 9756,
 15166,
 15262,
 13169,
 9663,
 8433,
 7341,
 10149,
 15335,
 15053,
 14940,
 15166,
 12785,
 8348,
 10324,
 17104,
 16706,
 15371,
 15111,
 13248,
 8664,
 9426,
 16583,
 17906,
 16789,
 16021,
 13294,
 8968,
 10768,
 17308,
 16680,
 17051,
 14947,
 13586,
 7990,
 10218,
 14836,
 15728,
 12534,
 16571,
 10137,
 7986,
 8332,
 15537,
 13403,
 13474,
 12473,
 9805,
 6362,
 6894,
 10918,
 11339,
 11370,
 11048,
 8512,
 5880,
 6949,
 11180,
 12003,
 10165,
 10250,
 8140,
 5434,
 7209,
 10434,
 11073,
 9778,
 10017,
 7832,
 5274,
 6860,
 9981,
 9691,
 9767,
 9628,
 7986,
 5499,
 6821,
 9890,
 10125,
 10574,
 10399,
 8046,
 5801,
 7496,
 11106,
 9722,
 11339,
 12222,
 9837,
 6480,
 7963,
 11573,
 12277,
 11875,
 10259,
 8397,
 6930,
 7474,
 11827,
 14848,
 14654,
 13422,
 12415,
 8575,
 9308,
 13342,
 13551,
 13213,
 12837,
 12023,
 8625,
 10509,
 14201,
 14118,
 13745,
 14360,
 13295,
 9673,
 11172,
 14497,
 15729,
 15003,
 14278,
 12574,
 9953,
 11086,
 13905,
 14205,
 14245,
 13738,
 13177,
 9902,
 10769,
 13622,
 13937,
 13139,
 13130,
 11650,
 10091,
 10644,
 14249,
 13344,
 12776,
 12775,
 11346,
 9552,
 8824,
 12752,
 12655,
 12761]

In [52]:
india_daily_death

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 -1,
 3,
 3,
 0,
 2,
 8,
 0,
 4,
 3,
 5,
 3,
 23,
 14,
 0,
 14,
 13,
 37,
 14,
 28,
 48,
 20,
 42,
 43,
 27,
 35,
 12,
 43,
 38,
 35,
 38,
 33,
 53,
 36,
 40,
 59,
 45,
 56,
 58,
 69,
 71,
 75,
 69,
 100,
 68,
 175,
 127,
 92,
 104,
 96,
 116,
 111,
 82,
 121,
 136,
 98,
 104,
 118,
 154,
 131,
 146,
 132,
 150,
 142,
 142,
 156,
 148,
 172,
 190,
 177,
 269,
 205,
 223,
 200,
 221,
 259,
 275,
 286,
 297,
 261,
 266,
 277,
 352,
 396,
 386,
 311,
 325,
 380,
 2003,
 334,
 336,
 375,
 306,
 445,
 312,
 465,
 418,
 407,
 384,
 410,
 380,
 418,
 507,
 434,
 379,
 442,
 613,
 425,
 466,
 483,
 487,
 475,
 519,
 550,
 501,
 553,
 582,
 605,
 688,
 671,
 543,
 681,
 585,
 650,
 1129,
 740,
 757,
 702,
 711,
 637,
 785,
 762,
 763,
 793,
 853,
 771,
 803,
 857,
 904,
 886,
 933,
 861,
 1007,
 871,
 834,
 942,
 1007,
 996,
 944,
 941,
 876,
 1091,
 978,
 983,
 945,
 912,
 836,
 848,
 967,
 1115,
 1057,
 1021,
 948,
 971,
 819,
 1045,
 1043,
 1096,
 1089,
 1065,
 1016,
 1133,
 1115,
 1172,
 1209,
 1201,
 1114,
 1136,
 1054,
 1290,
 1132,
 1174,
 1247,
 1133,
 1130,
 1053,
 1085,
 1129,
 1141,
 1089,
 1124,
 1039,
 776,
 1179,
 1181,
 1095,
 1069,
 940,
 903,
 884,
 986,
 971,
 964,
 926,
 918,
 816,
 706,
 730,
 680,
 895,
 837,
 1033,
 579,
 587,
 717,
 702,
 690,
 650,
 578,
 480,
 488,
 508,
 517,
 563,
 551,
 470,
 496,
 490,
 514,
 704,
 670,
 577,
 559,
 490,
 448,
 512,
 550,
 547,
 520,
 447,
 435,
 449,
 474,
 585,
 584,
 564,
 501,
 511,
 480,
 481,
 524,
 492,
 485,
 496,
 443,
 482,
 501,
 526,
 540,
 512,
 482,
 391,
 385,
 402,
 412,
 413,
 443,
 391,
 336,
 354,
 387,
 355,
 338,
 347,
 341,
 333,
 301,
 333,
 312,
 336,
 251,
 279,
 279,
 252,
 286,
 299,
 0,
 256,
 441,
 214,
 201,
 264,
 222,
 234,
 0,
 429,
 161,
 167,
 202,
 198,
 191,
 175,
 181,
 145,
 137,
 162,
 151,
 163,
 152,
 155,
 131,
 117,
 137,
 123,
 163,
 137,
 127,
 118,
 94,
 110,
 107,
 120,
 95,
 78,
 84,
 78,
 94,
 108,
 87,
 103,
 92,
 90,
 81,
 100,
 101,
 97,
 101,
 90,
 83,
 78,
 104,
 138,
 120,
 113,
 113,
 106,
 91,
 98,
 89,
 113,
 108,
 100,
 97,
 77,
 133,
 126,
 117,
 140,
 161,
 118,
 131,
 188,
 172,
 154,
 188,
 197,
 212,
 199,
 275,
 251,
 257,
 291,
 312,
 291,
 271,
 354,
 459,
 469,
 714,
 513,
 478,
 446,
 630,
 685,
 780,
 794,
 839,
 904,
 879,
 1027,
 1038,
 1185,
 1341,
 1501,
 1619,
 1761,
 2023,
 2104,
 2263,
 2624,
 2767,
 2812,
 2771,
 3293,
 3645,
 3498,
 3523,
 3689,
 3417,
 3449,
 3780,
 3980,
 3915,
 4187,
 4077,
 3769,
 3876,
 4205,
 4120,
 4000,
 3890,
 4077,
 4106,
 4329,
 4529,
 3874,
 4209,
 4194,
 3741,
 4454,
 3511,
 4157,
 3847,
 3660]

In [53]:
#recoveries
world_daily_recovery = daily_increase(total_recovered)
china_daily_recovery = daily_increase(china_recoveries)
italy_daily_recovery = daily_increase(italy_recoveries)
us_daily_recovery = daily_increase(us_recoveries)
spain_daily_recovery = daily_increase(spain_recoveries)
france_daily_recovery = daily_increase(france_recoveries)
germany_daily_recovery = daily_increase(germany_recoveries)
uk_daily_recovery = daily_increase(uk_recoveries)
india_daily_recovery = daily_increase(india_recoveries)

In [54]:
world_daily_recovery

[30,
 2,
 7,
 3,
 14,
 9,
 43,
 19,
 18,
 80,
 62,
 189,
 151,
 230,
 272,
 363,
 524,
 600,
 629,
 702,
 737,
 467,
 1143,
 1763,
 1339,
 1470,
 1717,
 1769,
 1769,
 2058,
 713,
 3997,
 505,
 1833,
 2678,
 2481,
 2892,
 3432,
 3071,
 2936,
 2884,
 2626,
 2942,
 2626,
 2068,
 2494,
 2337,
 1799,
 1907,
 2598,
 1323,
 1927,
 2372,
 3411,
 2055,
 2744,
 2487,
 1641,
 2445,
 4247,
 6217,
 468,
 9639,
 5779,
 8372,
 8785,
 8511,
 9456,
 15337,
 13590,
 15272,
 17143,
 15422,
 20412,
 13836,
 16709,
 23262,
 28882,
 25254,
 21738,
 26250,
 19383,
 27257,
 25074,
 36539,
 30883,
 26184,
 23866,
 31783,
 22178,
 34802,
 30085,
 28730,
 50029,
 27755,
 28812,
 27884,
 33212,
 42077,
 65116,
 38157,
 40651,
 32533,
 34086,
 36473,
 46119,
 39525,
 36413,
 53441,
 33809,
 46885,
 37042,
 55872,
 39711,
 48103,
 56411,
 41008,
 52916,
 52052,
 58970,
 51220,
 108547,
 54834,
 55527,
 63729,
 55152,
 63327,
 66863,
 77265,
 70450,
 76384,
 54925,
 104112,
 79091,
 70070,
 69165,
 72204,
 55109,
 151611,
 82270,
 79171,
 85879,
 79720,
 85892,
 70819,
 80275,
 97863,
 118831,
 81163,
 94990,
 115854,
 68686,
 91633,
 104055,
 115751,
 92884,
 105980,
 106286,
 89203,
 94571,
 117340,
 115914,
 284934,
 109888,
 195760,
 119363,
 123699,
 145033,
 158056,
 134618,
 139446,
 125692,
 111836,
 140323,
 142252,
 159806,
 152485,
 183421,
 150787,
 88058,
 159128,
 174696,
 179732,
 176230,
 228300,
 219812,
 143301,
 171383,
 170458,
 202586,
 213519,
 199606,
 180911,
 138724,
 222445,
 223657,
 221695,
 188807,
 192046,
 200244,
 178778,
 164211,
 305068,
 240645,
 163916,
 283242,
 168604,
 232954,
 211012,
 227595,
 217997,
 207790,
 168494,
 209917,
 216531,
 199421,
 231549,
 225734,
 207237,
 199118,
 211413,
 210240,
 200790,
 257962,
 219237,
 221369,
 213501,
 200988,
 211791,
 197548,
 201797,
 240267,
 216661,
 223670,
 222934,
 187848,
 228499,
 226287,
 229477,
 220211,
 251149,
 236985,
 237077,
 245478,
 219393,
 263413,
 255670,
 239208,
 262143,
 213879,
 222542,
 241284,
 248218,
 221542,
 172285,
 255601,
 222159,
 237468,
 232626,
 255191,
 219506,
 206790,
 195405,
 222640,
 200119,
 192445,
 212285,
 207327,
 203014,
 198283,
 201511,
 202531,
 211447,
 211222,
 226793,
 206734,
 211581,
 197258,
 239135,
 589705,
 265962,
 246751,
 255774,
 244329,
 257947,
 280137,
 251573,
 279319,
 303655,
 288361,
 299016,
 253240,
 257053,
 257360,
 380224,
 226239,
 302132,
 277819,
 230760,
 390730,
 433591,
 363110,
 374299,
 355424,
 339270,
 273724,
 411213,
 372179,
 437410,
 366876,
 381626,
 359706,
 318283,
 402256,
 476204,
 462926,
 426984,
 490617,
 435948,
 316044,
 413139,
 440771,
 426480,
 491226,
 478140,
 1504943,
 395119,
 -5989997,
 358164,
 362220,
 375409,
 317728,
 351586,
 276829,
 343220,
 363185,
 324140,
 314672,
 291606,
 408164,
 292388,
 298426,
 353095,
 388245,
 275151,
 280378,
 301292,
 268482,
 290408,
 315361,
 313125,
 323931,
 297263,
 330245,
 270550,
 290288,
 343557,
 366061,
 372845,
 320622,
 317055,
 315715,
 318753,
 402944,
 327771,
 366139,
 381757,
 316493,
 310957,
 314441,
 329543,
 340769,
 315659,
 364107,
 351166,
 288899,
 272642,
 350190,
 329847,
 293989,
 281287,
 294557,
 277435,
 232834,
 371608,
 269308,
 276085,
 287599,
 246243,
 195431,
 288613,
 235405,
 293941,
 236618,
 234636,
 269216,
 217257,
 182570,
 278630,
 209459,
 227692,
 260268,
 250722,
 175177,
 214926,
 270104,
 229408,
 250280,
 226360,
 236503,
 238320,
 274558,
 262233,
 235356,
 272617,
 268556,
 252532,
 245688,
 289879,
 266485,
 264536,
 269076,
 279061,
 258211,
 280099,
 334629,
 313142,
 335642,
 311817,
 364586,
 305253,
 328788,
 304436,
 335243,
 382509,
 344786,
 320207,
 366001,
 348188,
 347813,
 369996,
 483305,
 395259,
 453713,
 384994,
 530472,
 394732,
 486462,
 446890,
 444402,
 504117,
 518536,
 580191,
 535375,
 604837,
 512300,
 636296,
 639832,
 576291,
 533814,
 687366,
 680904,
 596665,
 707316,
 686596,
 682450,
 693014,
 643489,
 656900,
 713482,
 675612,
 696129,
 711005,
 662793,
 628686,
 751004,
 647549,
 690117,
 665347,
 642537,
 667404,
 744462,
 743113,
 698027,
 636689,
 614788,
 616761,
 501971,
 627592,
 577063,
 553181,
 698481]

In [55]:
india_daily_recovery

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 9,
 0,
 1,
 0,
 1,
 5,
 3,
 4,
 0,
 13,
 3,
 2,
 28,
 11,
 11,
 7,
 21,
 25,
 43,
 1,
 37,
 0,
 146,
 46,
 85,
 114,
 154,
 195,
 111,
 101,
 178,
 73,
 336,
 273,
 422,
 391,
 419,
 702,
 395,
 642,
 486,
 441,
 584,
 614,
 610,
 690,
 631,
 939,
 812,
 956,
 1072,
 1295,
 1189,
 1445,
 1111,
 1414,
 1668,
 1580,
 1871,
 1980,
 1569,
 2289,
 3966,
 2571,
 2438,
 3076,
 3113,
 3131,
 3271,
 2561,
 3307,
 3014,
 3571,
 3472,
 3171,
 11707,
 4309,
 4916,
 3902,
 4531,
 3786,
 4379,
 4783,
 5462,
 5153,
 5247,
 5575,
 536,
 11989,
 7135,
 8049,
 7419,
 10215,
 6922,
 7390,
 10386,
 9120,
 13897,
 9468,
 10994,
 10495,
 13012,
 13940,
 10244,
 13832,
 12010,
 13099,
 13090,
 11948,
 20032,
 14335,
 14856,
 15350,
 15501,
 16897,
 19547,
 19135,
 19873,
 19232,
 18853,
 17989,
 20572,
 20736,
 22989,
 17994,
 23672,
 22664,
 24491,
 28472,
 29557,
 34602,
 32223,
 36141,
 31995,
 33598,
 36863,
 31706,
 35613,
 39026,
 51255,
 40574,
 44306,
 51706,
 46121,
 49769,
 48900,
 53879,
 54859,
 47746,
 56110,
 56383,
 55573,
 57381,
 53322,
 57584,
 57829,
 60145,
 58848,
 62282,
 63631,
 57989,
 57469,
 66550,
 53754,
 65432,
 60177,
 65050,
 64935,
 60868,
 65081,
 62026,
 68584,
 66659,
 70072,
 73642,
 69564,
 73521,
 74894,
 72939,
 70880,
 81533,
 78399,
 77512,
 79292,
 82961,
 82719,
 87472,
 95880,
 94612,
 93356,
 101468,
 89746,
 87374,
 81177,
 93420,
 92043,
 74893,
 84877,
 86428,
 85376,
 78877,
 75628,
 82260,
 76737,
 75787,
 82203,
 83011,
 78365,
 82753,
 89154,
 71559,
 77760,
 74632,
 81514,
 70338,
 70816,
 72614,
 66399,
 69720,
 61775,
 79415,
 73979,
 67549,
 62077,
 59105,
 63842,
 58439,
 56480,
 57386,
 59454,
 58684,
 53285,
 58323,
 53357,
 55331,
 54157,
 53920,
 49082,
 48405,
 42033,
 54377,
 52718,
 49079,
 47992,
 42156,
 43851,
 40791,
 44739,
 48493,
 44807,
 49715,
 43493,
 41024,
 42314,
 37816,
 36367,
 39379,
 41452,
 42298,
 45333,
 41985,
 43062,
 40726,
 42916,
 42533,
 41970,
 39109,
 39045,
 36635,
 37725,
 37503,
 33519,
 33136,
 30695,
 34477,
 33813,
 33291,
 31087,
 29885,
 29690,
 25709,
 30376,
 26895,
 29791,
 24661,
 22274,
 21430,
 21131,
 24900,
 26572,
 26139,
 0,
 23181,
 43849,
 19557,
 29091,
 21314,
 19587,
 20539,
 0,
 38552,
 16959,
 18385,
 17817,
 17652,
 15975,
 16977,
 17170,
 14457,
 17411,
 16988,
 19965,
 17996,
 17136,
 15948,
 13298,
 15901,
 13320,
 14301,
 20746,
 14794,
 13963,
 11874,
 13423,
 14225,
 17824,
 15853,
 14488,
 11805,
 11904,
 14016,
 13087,
 11764,
 15858,
 11395,
 11106,
 9489,
 11805,
 11833,
 11987,
 10896,
 10307,
 11667,
 9695,
 13255,
 14037,
 11799,
 12179,
 12771,
 11718,
 11283,
 12469,
 13123,
 14031,
 13819,
 14232,
 14394,
 14278,
 16596,
 20652,
 18100,
 15157,
 19957,
 16637,
 17455,
 20191,
 17741,
 17741,
 20654,
 23653,
 22956,
 21180,
 29785,
 23907,
 26490,
 32987,
 30386,
 28739,
 32231,
 37028,
 41280,
 40382,
 50356,
 44202,
 60048,
 52847,
 50143,
 59856,
 59258,
 61899,
 77567,
 90584,
 75086,
 97168,
 82339,
 93528,
 118302,
 123354,
 138418,
 144179,
 154748,
 167474,
 178841,
 193279,
 219838,
 217113,
 219272,
 251707,
 261151,
 269500,
 297678,
 299988,
 307865,
 300454,
 320567,
 338229,
 329323,
 331507,
 318609,
 386404,
 353858,
 356082,
 355338,
 352181,
 344776,
 353299,
 362437,
 378741,
 422436,
 389851,
 369077,
 357295,
 357630,
 355102,
 302544,
 326850,
 295955,
 283135,
 259459]

In [56]:
unique_countries =  list(latest_data['Country_Region'].unique())
unique_countries

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burma',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo (Brazzaville)',
 'Congo (Kinshasa)',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Diamond Princess',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Holy See',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Korea, South',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'MS Zaandam',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan*',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'US',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'West Bank and Gaza',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'Kiribati']